bcgov/PSP

.vscode/launch.json, .vscode/settings.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/layout/Header/ErrorModal.tsx, frontend/src/components/layout/Header/Header.test.tsx, frontend/src/components/layout/Header/Header.tsx, frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap, frontend/src/tenants/CITZ/config.ts, frontend/src/tenants/ITenantConfig.ts, frontend/src/tenants/MOTI/config.ts, frontend/src/tenants/index.ts, frontend/src/tenants/tenant.test.ts, frontend/src/tenants/tenant.ts
Simple tenant configuration provides a way to present different information based on the environment variable selecting a tenant.
Add unit tests
Fix vs-code Jest-Runner `Run` plugin
- I couldn't resolve the Jest-Runner `Debug` plugin regrettably.  Although I did find a way to make it run, it would never step into the code.  Additionally if it was configured to "work", the `Run` button would stop and it would also impact the normal command line testing...
=> psp-698 Tenant Configuration

backend/api/Helpers/Middleware/LogRequestMiddleware.cs, backend/api/Helpers/Middleware/LogResponseMiddleware.cs, backend/api/Pims.Api.csproj, backend/api/Startup.cs
To assist with debugging issues response will now be logged.
Additionally, the body of both requests and responses will be logged if the logging level is set at Debug.
=> PSP-690 API Response Logging

.vscode/settings.json, backend/tests/unit/dal/Libraries/Geocoder/GeocoderServiceTest.cs, backend/tests/unit/dal/Libraries/Geocoder/ParameterExtensionsTest.cs, backend/tests/unit/dal/Libraries/Geocoder/ServiceCollectionExtensionsTest.cs, backend/tests/unit/dal/Libraries/Keycloak/ServiceCollectionExtensionsTest.cs, backend/tests/unit/dal/Libraries/Notifications/ServiceCollectionExtensionsTest.cs
Adding unit tests for the backend libraries.
=> PSP-694 Improve code coverage

backend/core/Pims.Core.csproj, backend/geocoder/Pims.Geocoder.csproj, tools/converters/excel/Converters/GeoLocationConverter.cs, tools/converters/excel/Pims.Tools.Converters.ExcelConverter.csproj, tools/core/Pims.Tools.Core.csproj, tools/import/Pims.Tools.Import.csproj, tools/keycloak/sync/Pims.Tools.Keycloak.Sync.csproj
I forgot to upgrade the packages in the tools last sprint.
=> PSP-665 Upgrade tool packages

frontend/src/layouts/Footer.tsx, openshift/4.0/templates/app/deploy.yaml
The footer wasn't getting the configured colour correctly.  
Fix app deployment configuration so that the branding will work.
=> PSP-684 Fix footer

frontend/src/components/layout/AppNavBar/AppNavBar.CITZ.test.tsx, frontend/src/components/layout/AppNavBar/AppNavBar.MOTI.test.tsx, frontend/src/components/layout/AppNavBar/AppNavBar.tsx, frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.CITZ.test.tsx.snap, frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.MOTI.test.tsx.snap, frontend/src/tenants/FeatureToggle/FeatureToggle.test.tsx, frontend/src/tenants/FeatureToggle/FeatureToggle.tsx, frontend/src/tenants/FeatureToggle/index.ts
PR changes:
* Created component to show/hide UI sections based on the current tenant 
```jsx
// Renders children components for MOTI
<FeatureToggle tenant="MOTI"> ... </FeatureToggle>
// Removes children from UI for MOTI
<FeatureToggle tenant="MOTI" hide> ... </FeatureToggle>
```
* Added unit tests
* Split `NavBar` unit tests into separate files per tenant: **NavBar.CITZ.test.tsx** and **NavBar.MOTI.test.tsx**
* Fixed missing dependency updates for the backend
=> PSP-723 Disable "Submit Property"  feature from the ribbon

frontend/src/components/layout/AppNavBar/AppNavBar.CITZ.test.tsx, frontend/src/components/layout/AppNavBar/AppNavBar.MOTI.test.tsx, frontend/src/components/layout/AppNavBar/AppNavBar.tsx, frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.CITZ.test.tsx.snap, frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.MOTI.test.tsx.snap
* Removed Home button for new users without any roles (who can only request access to PIMS)
* Added unit tests to cover new scenarios
-------
=> PSP-997 Remove Home Button from Access Request Page

backend/api/Pims.Api.csproj
=> PSP-1008 Update version v01.10.5

backend/Dockerfile
Need to update the `Dockerfile` whenever we add a new C# project to the backend. 
I wish there was a way to automate this...
=> Fix docker build

frontend/src/features/account/LoginStyled.tsx, frontend/src/features/account/__snapshots__/Login.test.tsx.snap, frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
The background image was having issues with cropping and scrolling in some browser sizes, or odd window sizes.
During testing I had inconsistent results that hopefully don't show up. However it appears now it scales better.
=> PSP-1252 Fix background image style

backend/tests/unit/dal/Services/Admin/AddressServiceTest.cs, backend/tests/unit/dal/Services/Admin/AdministrativeAreaServiceTest.cs, backend/tests/unit/dal/Services/Admin/AgencyServiceTest.cs, backend/tests/unit/dal/Services/Admin/ProjectServiceTest.cs, backend/tests/unit/dal/Services/Admin/PropertyClassificationTest.cs, backend/tests/unit/dal/Services/Admin/ProvinceServiceTest.cs, backend/tests/unit/dal/Services/Admin/RoleServiceTest.cs, backend/tests/unit/dal/Services/Admin/UserServiceTest.cs, backend/tests/unit/dal/Services/Admin/WorkflowServiceTest.cs
Splitting off some of the tests instead of submitting one big pile of unit tests - some of these tests are still being worked at to achieve 100% coverage for the service
=> Unit tests backend

frontend/.prettierignore, openshift/4.0/pipelines/Jenkinsfile.cicd, openshift/4.0/scripts/oc-build.sh, openshift/4.0/scripts/oc-deploy.sh, openshift/4.0/templates/api/README.md, openshift/4.0/templates/api/build.yaml, openshift/4.0/templates/api/deploy-alt-routes.yaml, openshift/4.0/templates/api/deploy-routes.yaml, openshift/4.0/templates/api/deploy-swagger.yaml, openshift/4.0/templates/api/deploy.yaml, openshift/4.0/templates/app/README.md, openshift/4.0/templates/app/deploy-alt-routes.yaml, openshift/4.0/templates/app/deploy-routes.yaml, openshift/4.0/templates/app/deploy.yaml
Adding support for multiple instances within a single OpenShift namespace. 
This allows us to have a "TEST" instance within the DEV namespace in OpenShift while leaving the TEST namespace for UAT.
=> PSP-1246 DevOps pipeline 'test' to TEST

backend/tests/unit/dal/Services/Admin/BuildingContructionTypeServiceTest.cs, backend/tests/unit/dal/Services/Admin/ProjectRiskServiceTest.cs, backend/tests/unit/dal/Services/Admin/TierLevelServiceTest.cs
Splitting off some more tests. 
Also working on going through the tests that are > 0% but < 100% but have a few failures I am trying to figure out. 
Will try and keep these PRs smaller since I know they are fun to read 😄
=> DAL Unit Tests

frontend/public/basemaps.json, frontend/public/index.html, openshift/s2i/nginx-runtime/nginx.conf.template
=> PSP-1187 Change Base Map to BC Data Warehouse 

Makefile, backend/api/Areas/Admin/Controllers/AccessRequestController.cs, backend/api/Controllers/UserController.cs, frontend/src/features/admin/access-request/AccessRequestPage.CITZ.test.tsx, frontend/src/features/admin/access-request/AccessRequestPage.tsx, frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.CITZ.test.tsx.snap, frontend/src/features/admin/access/ManageAccessRequests.test.tsx, frontend/src/features/admin/access/ManageAccessRequests.tsx, frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap, frontend/src/features/admin/access/constants/constants.tsx, frontend/src/features/admin/edit-user/EditUserPage.test.tsx, frontend/src/features/admin/edit-user/EditUserPage.tsx, frontend/src/interfaces/accessRequests.ts, frontend/src/mocks/filterDataMock.ts, frontend/src/store/slices/accessRequests/accessRequestsSlice.ts, frontend/src/utils/YupSchema.ts
Reverts bcgov/PSP#95
These changes are making it far more complicated to complete the DB schema changes.  I'm proposing we default to the TRAN agency.
=> Revert "PSP-1433 Agency error appears when submitting access request"

backend/tests/unit/dal/Services/Admin/BuildingServiceTest.cs, frontend/package-lock.json, frontend/src/components/common/ErrorModal.test.tsx, frontend/src/components/common/__snapshots__/ErrorModal.test.tsx.snap, frontend/src/features/help/components/HelpBox.test.tsx, frontend/src/features/help/components/HelpSubmitBox.test.tsx, frontend/src/features/help/components/__snapshots__/HelpBox.test.tsx.snap, frontend/src/features/help/components/__snapshots__/HelpSubmitBox.test.tsx.snap, frontend/src/features/help/containers/HelpContainer.test.tsx, frontend/src/features/help/containers/HelpModalContentContainer.test.tsx, frontend/src/features/help/containers/__snapshots__/HelpContainer.test.tsx.snap, frontend/src/features/help/containers/__snapshots__/HelpModalContentContainer.test.tsx.snap, frontend/src/utils/TestCommonWrapper.tsx
Have some more tests in my stash that I can put up as well (was working through the common components folder), just need to go through them and split off the ones that are still in PSP!
=> Help desk tests

frontend/src/components/layout/Header/UserProfile.tsx
also removed the roles section if empty, and added an alignment correction to prevent cutoff on small devices.
=> psp-1004 dropdown does not scale.

frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.test.tsx, frontend/src/constants/index.ts, frontend/src/features/admin/agencies/EditAgencyPage.tsx, frontend/src/interfaces/IAccessRequest.ts, frontend/src/mocks/filterDataMock.ts, frontend/src/store/slices/agencies/agencyActionCreator.test.tsx, frontend/src/store/slices/agencies/useAgencies.ts, frontend/src/store/slices/lookupCodes/interfaces/ILookupCode.ts, frontend/src/store/slices/properties/useProperties.test.tsx
Subsequent updates to the agency form will no longer cause concurrency issues.
Note that the bomb icon will still be displayed for actual concurrency issues. I'm not convinced that this needs to be fixed given that we also display a friendly error message for this case.
=> PSP-1444 Fix Agency Administration - Concurrency

frontend/package.json, frontend/src/components/Table/PageSizeSelector.test.tsx, frontend/src/components/Table/Table.tsx, frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap, frontend/src/components/layout/Header/Header.test.tsx, frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.test.tsx, frontend/src/features/admin/access/ManageAccessRequests.test.tsx, frontend/src/features/admin/access/components/Details.test.tsx, frontend/src/features/admin/agencies/EditAgencyPage.test.tsx, frontend/src/features/admin/agencies/ManageAgencies.test.tsx, frontend/src/layouts/Header.test.tsx, frontend/src/store/slices/agencies/agencyActionCreator.test.tsx, frontend/src/store/slices/users/usersReducer.test.tsx
now run tsc before tests, to ensure that tests don't have tsc issues (since jest-ts ignores ts warnings).
Fix all current test typescript issues.
=> Test tsc corrections.

backend/api/Areas/Admin/Mapping/User/RoleMap.cs, openshift/3.11/MULTIPLE_INSTANCES.md, openshift/3.11/templates/pims-api/deploy.yaml, openshift/3.11/templates/pims-app/deploy.yaml, openshift/3.11/templates/resources/api-sso-configMap.yaml, openshift/3.11/templates/resources/app-sso-configMap.yaml, openshift/4.0/templates/app/deploy.yaml, test/Postman/pims-api-collection.json, tools/import/appsettings.Development.json, tools/import/appsettings.Production.json, tools/import/appsettings.Test.json, tools/import/appsettings.json, tools/keycloak/sync/SyncFactory.cs, tools/keycloak/sync/appsettings.development.json, tools/keycloak/sync/appsettings.test.json, tools/keycloak/sync/realm.development.json, tools/keycloak/sync/realm.test.json
Configuration for the Keycloak Sync tool was still setup for CITZ PIMS.
=> PSP-911 Update Keycloak Sync Config

openshift/4.0/templates/api/deploy.yaml, openshift/4.0/templates/app/deploy.yaml, tools/keycloak/sync/realm.development.json
1) Correct keycloak realm for dev.
2) At TZ to deployment configs so logs are in PDT TZ.
=> configuration updates

etl/PAIMS_PIMS/PAIMS_PIMS/PAM_AREA_UNIT_Load.dtsx
I missed some unicode conversions in my last PR, this corrects that issue.
=> correct unicode conversion.

frontend/src/components/common/GenericModal.test.tsx, frontend/src/components/common/TooltipIcon.tsx, frontend/src/components/common/__snapshots__/GenericModal.test.tsx.snap, frontend/src/components/common/form/ParentSelect.test.tsx, frontend/src/components/common/form/__snapshots__/FastCurrencyInput.test.tsx.snap, frontend/src/components/menu/Menu.test.tsx, frontend/src/components/menu/__snapshots__/Menu.test.tsx.snap, frontend/src/features/admin/agencies/AgencyFilterBar.test.tsx, frontend/src/features/admin/agencies/__snapshots__/AgencyFilterBar.test.tsx.snap, frontend/src/features/admin/users/components/RowActions.tsx, frontend/src/features/mapSideBar/components/InventoryFormButtons.test.tsx, frontend/src/features/mapSideBar/components/MapSideBarLayout.test.tsx, frontend/src/features/mapSideBar/components/__snapshots__/InventoryFormButtons.test.tsx.snap, frontend/src/features/mapSideBar/components/__snapshots__/MapSideBarLayout.test.tsx.snap, frontend/src/features/properties/components/GeocoderAutoComplete.test.tsx, frontend/src/features/properties/components/__snapshots__/GeocoderAutoComplete.test.tsx.snap, frontend/src/features/properties/filter/PropertyFilterAgencyOptions.test.tsx, frontend/src/features/properties/filter/PropertyFilterOptions.test.tsx, frontend/src/features/properties/filter/__snapshots__/PropertyFilterAgencyOptions.test.tsx.snap, frontend/src/features/properties/filter/__snapshots__/PropertyFilterOptions.test.tsx.snap
More tests I had in stash that still apply after the removal of various frontend components
Updates: Just adding new ones I've been creating as well to this PR
=> Frontend Unit Tests

backend/api/Pims.Api.csproj, frontend/package.json, frontend/public/index.html, frontend/src/components/maps/leaflet/LayersControl/data.ts, openshift/s2i/nginx-runtime/nginx.conf.template
* Update GeoServer url
* IS7 work items
=> Release v0.2.0.7.2

frontend/public/index.html, openshift/s2i/nginx-runtime/nginx.conf.template
(cherry picked from commit 482aa1db987f3aea65f91031e6df5f9df4514c00)
=> modify csp based on conversation with Jeremy, Alejandro. (#87)

frontend/src/features/admin/agencies/EditAgencyPage.test.tsx, frontend/src/features/admin/edit-user/EditUserPage.test.tsx, frontend/src/features/admin/edit-user/EditUserPage.tsx, frontend/src/features/help/components/HelpSubmitBox.test.tsx, frontend/src/features/help/components/__snapshots__/HelpSubmitBox.test.tsx.snap, frontend/src/features/help/containers/HelpModalContentContainer.test.tsx, frontend/src/features/help/containers/__snapshots__/HelpModalContentContainer.test.tsx.snap, frontend/src/features/properties/filter/PropertyFilter.test.tsx
Cleanup various console warnings from our unit tests. Still struggling with one of the files so I took it out for now and will work on it separately.
=> Clean up test warnings

frontend/src/components/layout/AppNavBar/AppNavBar.test.tsx, frontend/src/components/layout/AppNavBar/AppNavBar.tsx, frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.test.tsx.snap
remove unused features for release 1
=> Psp 1635 navbar updates

frontend/src/features/help/components/HelpModal.tsx, frontend/src/features/help/components/HelpSubmitBox.scss, frontend/src/features/help/components/text/LandingFilterHelpText.tsx, frontend/src/features/help/components/text/LandingMapHelpText.tsx, frontend/src/features/help/components/text/LandingNavigationHelpText.tsx
Update wording of help to be consistent with PSP requirements.
Ensure that vertical overflow of help form is handled appropriately.
Ensure that form fields/labels are aligned correctly.
=> Psp 1322 help updates

Makefile, backend/api/Pims.Api.csproj, build/bump-version.js, frontend/package.json
Add **make** support for release commands:
```bash
make version
make bump
```
=> Release IS8 to DEV

backend/api/Pims.Api.csproj, frontend/package.json, frontend/src/components/common/ApiVersionInfo.test.tsx, frontend/src/components/common/ApiVersionInfo.tsx
=> Release IS8 to DEV - version 0.2.0-8.2

backend/api/Pims.Api.csproj, frontend/package.json
=> PSP-1780 DEPLOY IS9 to DEV Environment

.github/workflows/app-logging.yml, database/mssql/scripts/dbscripts/README.md
Updated the README.md file to reflect the Git build
=> Updated README file for dbscripts

backend/api/Pims.Api.csproj, frontend/package.json
=> DEPLOY IS10 to DEV Environment

frontend/src/components/layout/Header/Header.test.tsx, frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx, frontend/src/components/maps/leaflet/Map.test.tsx, frontend/src/components/maps/leaflet/Map.tsx, frontend/src/constants/API.ts, frontend/src/features/account/LoginStyled.tsx, frontend/src/features/account/__snapshots__/Login.test.tsx.snap, frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap, frontend/src/hooks/pims-api/useApi.test.ts, frontend/src/hooks/pims-api/useApi.ts, frontend/src/hooks/pims-api/useApiAccessRequests.ts, frontend/src/hooks/pims-api/useApiHealth.ts, frontend/src/hooks/pims-api/useApiLeases.ts, frontend/src/hooks/pims-api/useApiLookupCodes.ts, frontend/src/hooks/pims-api/useApiLtsa.tsx, frontend/src/hooks/pims-api/useApiProperties.ts, frontend/src/hooks/pims-api/useApiTenants.ts, frontend/src/hooks/pims-api/useApiUsers.ts
The view is expecting numerical pids/pins, and doesn't appear to support leading zeros on the geoserver side.
=> support searching by pid/pin with leading 0's.

backend/api/Areas/Property/Mapping/Property/LeaseMap.cs, backend/api/Areas/Property/Mapping/Property/PropertyMap.cs, backend/api/Areas/Property/Models/Property/LeaseModel.cs, backend/api/Areas/Property/Models/Property/PropertyModel.cs, backend/dal/Helpers/Extensions/PropertyExtensions.cs, backend/dal/Services/PropertyService.cs, backend/tests/core/Entities/PropertyHelper.cs, frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx, frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx, frontend/src/components/maps/leaflet/InfoSlideOut/LeaseAttributes.tsx, frontend/src/features/leases/components/LeaseAndLicenseListView.test.tsx, frontend/src/interfaces/ILease.ts, frontend/src/interfaces/IProperty.ts, frontend/src/interfaces/index.ts
Shares backend api functionality with psp-1772
=> Psp 1839 add property lease details to slideout

.github/.trufflehog3.yml, .github/workflows/credentials-comment-pr.yml, .github/workflows/credentials-scan.yml, auth/keycloak/config/realm-export.json, build/README.md, build/secops_report.sh, frontend/public/tenants/tenant.json
Use this PR to discuss what to do with the potential secrets remaining in the source code.
=> Discuss exceptions to security scans

backend/api/Pims.Api.csproj, frontend/package.json
Fixes:
- PSP-1936
- PSP-1370 PID search bug.
=> Release IS9 v0.2.0-9.2 to TST

frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.test.tsx, frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.tsx, frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/HeaderActions.test.tsx.snap, frontend/src/components/maps/leaflet/PointClusterer.tsx, frontend/src/components/maps/leaflet/mapUtils.tsx, frontend/src/features/properties/filter/PropertyFilter.tsx, frontend/src/utils/propertyUtils.ts
cherry pick all relevant commits to test since https://github.com/bcgov/PSP/commit/95b6fd7e5f4ebf80792b17fa8bcb0077704f571d
=> reverse merge test to dev

.github/workflows/image-scan-analysis.yml
This should resolve the blocked PR to test.
=> Update image scan github action.

Makefile, docker-compose.yml, frontend/src/App.scss, frontend/src/components/Table/Table.tsx, frontend/src/components/common/Snackbar.tsx, frontend/src/components/maps/leaflet/__snapshots__/Map.test.tsx.snap, frontend/src/components/maps/leaflet/styles.ts, frontend/src/features/admin/access-request/AccessRequestPage.scss, frontend/src/features/admin/access-request/AccessRequestPage.tsx, frontend/src/features/admin/access/ManageAccessRequests.scss, frontend/src/features/admin/edit-user/EditUserPage.scss, frontend/src/features/admin/edit-user/EditUserPage.tsx, frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap, frontend/src/features/admin/users/ManageUsers.tsx, frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap, frontend/src/features/admin/users/styles.ts, frontend/src/features/properties/list/PropertyListView.scss, frontend/src/features/properties/list/PropertyListView.tsx, frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap, frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap, frontend/src/layouts/AuthLayout.tsx, frontend/src/layouts/styles.ts
Other updates:
- new **make start-infra** command to facilitate starting containers required for local dev (database, keycloak and geoserver)
- is just a shortcut for **make start n=keycloak**, **make start n=database**, etc
- Updated some styles to be consistent with new style guide.
- Removed unnecessary (and error prone) CSS calc for container heights by properly applying grid and flex values
=> PSP-2018 Property List View pagination bugfix

frontend/src/components/common/form/TextArea.tsx, frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
Needs to be applied to the inner class not the div.
=> Improvement description text fix

.github/workflows/version.yml
Small PR to fix minor issues with the auto-versioning GitHub action
=> Fix auto-versioning action

frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap, frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap, frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap, frontend/src/features/leases/detail/LeasePages/tenant/Tenant.test.tsx, frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx, frontend/src/features/leases/detail/LeasePages/tenant/TenantNotes.tsx, frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap, frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap, frontend/src/features/leases/detail/styles.ts
Adjust notes so it scales properly and aligns with other sections - merging to test as it was FT this sprint.
=> PSP-2308: Adjust for scaling

frontend/src/features/contacts/contact/detail/Organization.tsx, frontend/src/features/contacts/contact/detail/Person.tsx
Update based on the demo feedback
=> Fixed link between Orgs and Persons

openshift/4.0/pipelines/Jenkinsfile.cicd.prod
Recommend testing this with a soft release of 10.2 -> 10.2
=> Add the ability to manually specify release versions.

frontend/src/features/leases/list/LeaseListView.tsx
Excel button was previously downloading CSV
=> PSP-2543: Excel button downloading CSV

frontend/src/features/contacts/contact/detail/Person.tsx
Fix to correct work phone appearing correctly
=> PSP-2587: Fix for work phone appearing as home

backend/api/Pims.Api.csproj, frontend/package.json
update current minor release
update patch release to reflect UAT fix.
=> Manually increment versions

database/mssql/scripts/dbscripts/PSP_PIMS_S17_00/Test Data/TENANT_TEST_DATA.sql
Removed duplicate entry that was conflicting with seed data, also placing in new appropriate location
=> Fix tenant test data

backend/api/Pims.Api.csproj, frontend/package.json, frontend/src/AppRouter.tsx, frontend/src/utils/utils.ts
(I will merge this after 2658)
=> psp-2660 add simple retry to lazy load promise.

frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx, frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
Tweaks so validation fired for contact methods in addition to other required fields.
**Previously:**
**Now:**
=> PSP-2819: Contact Method Validation Bug Fix

scripts/gen-env-files.sh
-Remove dead import .env
-Remove unused api postgres .env
-Add missing parameter for sql server make scripts.
=> Update gen env files.

etl/LISOS_PIMS/LISOS_PIMS/LISOS_Load.dtsx, etl/LISOS_PIMS/LISOS_PIMS/LISOS_PIMS.dtproj
create candidate key using tfa and ps file number to uniquely identify LISOS lease
ensure that null notes or comments are written correctly
=> psp-2827 correct issues with LISOS etl.

backend/dal/Repositories/LeaseRepository.cs, backend/dal/Services/LeaseTermService.cs, backend/tests/unit/dal/Services/LeaseTermServiceTest.cs, frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx, frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
merge last two test bugfixes back to dev.
=> Backmerge test to dev

backend/api/Areas/Organizations/Controllers/OrganizationController.cs, backend/api/Areas/Organizations/Mapping/Organization/AddressMap.cs, backend/api/Areas/Organizations/Mapping/Organization/ContactMethodMap.cs, backend/api/Areas/Organizations/Mapping/Organization/OrganizationMap.cs, backend/api/Areas/Organizations/Mapping/Organization/PersonMap.cs, backend/api/Areas/Organizations/Models/Organization/OrganizationAddressModel.cs, backend/api/Areas/Organizations/Models/Organization/OrganizationModel.cs, backend/api/Areas/Organizations/Models/Organization/PersonSummaryModel.cs, backend/api/Areas/Persons/Controllers/PersonController.cs, backend/api/Areas/Persons/Mapping/Person/ContactMethodMap.cs, backend/api/Models/Contact/AddressModel.cs, backend/api/Models/Contact/ContactMethodModel.cs, backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs, backend/dal/IPimsRepository.cs, backend/dal/IPimsService.cs, backend/dal/PimsRepository.cs, backend/dal/PimsService.cs, backend/dal/Repositories/Interfaces/IOrganizationRepository.cs, backend/dal/Repositories/OrganizationRepository.cs, backend/dal/Services/Interfaces/IOrganizationService.cs, backend/dal/Services/OrganizationService.cs, backend/entities/Organization.cs, backend/tests/unit/api/Controllers/Organization/OrganizationControllerTest.cs
This is the backend portion of UPDATE ORGANIZATION. As such, there is no UI (currently) to capture updated data for an organization. However I tested the API endpoints with Postman and they return the JSON data that is expected.
I have included a small sample of backend unit tests in this PR. More tests will come in either this or subsequent PRs.
=> PSP-2300 update organization - BACKEND

.github/workflows/ci-cd-pims-test.yml, openshift/4.0/scripts/oc-tag.sh
* PSP-2846
* fix destination value
* Delete tag-test.sh
(cherry picked from commit f339e172e5d0606ce4f97d18f63f7fb8e7b659e1)
=> PSP-2846 - GitHub action "CI-CD PIMS Test" (#902)

frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx, frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap, frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap, frontend/src/features/contacts/contact/detail/Organization.tsx, frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap, frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap, frontend/src/features/properties/filter/PropertyFilter.tsx, frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap, frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap, frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
=> Updated sizing of property filter

frontend/src/components/Table/PageSizeSelector.tsx, frontend/src/components/Table/Table.scss, frontend/src/components/Table/Table.tsx, frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap, frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx, frontend/src/components/contact/ContactManagerView/ContactResultComponent/ContactResultComponent.tsx, frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap, frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap, frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap, frontend/src/features/admin/users/ManageUsers.tsx, frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap, frontend/src/features/contacts/list/ContactListPage.tsx, frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap, frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap, frontend/src/features/leases/list/LeaseListView.tsx, frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx, frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap, frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap, frontend/src/features/properties/list/PropertyListView.tsx, frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
=> Count on table pagination | Features/psp 2691

backend/api/Areas/Leases/Models/Search/LeaseFilterModel.cs
=> Added missing pagination fields

frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx, frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
- Fix missing claim check for add contact button
- Update snapshot
=> Enforce proper claims on Contact List view

backend/api/Program.cs, backend/api/ltsa.Development.json, backend/api/ltsa.Local.json, backend/api/ltsa.Test.json, backend/api/ltsa.json, backend/ltsa/Configuration/LtsaOptions.cs, test/Postman/pims-api-collection.json
Updates to LTSA urls, corresponding postman tests.
=> psp-2802 update configuration with updated urls, tests.

frontend/src/features/leases/list/LeaseSearchResults/LeaseProperties.tsx, frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
=> Made PID and PIN displaying optional

.github/workflows/release.yml
Release notifications are now working
=> PSP-2626 Fix release github action

backend/api/Startup.cs
fixes: 
tested locally to validate existing signature validation works and other algorithms are rejected.
=> Weak Signature in JWT

frontend/src/features/contacts/contact/detail/Person.test.tsx, frontend/src/features/contacts/contact/detail/Person.tsx
=> Update view person to support PERSPHONE.

.github/workflows/api-dotnetcore.yml
Need to use latest version to support NET 6
=> Fix dotnet-sonar

frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx, frontend/src/features/mapSideBar/tabs/SectionField.tsx, frontend/src/features/mapSideBar/tabs/SectionStyles.tsx
Added common styles and a component that represents label and value pairs
=> Common styles - PSP-3016

frontend/src/components/common/GenericModal.tsx
=> Switched the order of modal buttons [cancel] [ok]

backend/api/Repositories/MayanDocumentRepository.cs, backend/api/appsettings.Local.json, frontend/src/pages/TestFileManagement.tsx
Also fixes an issue with the mayan upload API
=> Mayan test page improvements

backend/api/Pims.Api.csproj, backend/dal/Repositories/LeaseRepository.cs, frontend/package.json
Handle issue with extremely large leases.
=> psp-3042 correct issue with lease max page size.

frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.tsx, frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
=> Fixed label on return deposits payee

backend/api/Pims.Api.csproj, backend/dal/Helpers/Extensions/ContactExtensions.cs, frontend/package.json, frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.tsx, frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
Improved search of contacts by taking into account partial searches of person names
Filter type
=> Partial searches of person names & type filters fix

frontend/package-lock.json, frontend/src/components/layout/SideNavBar/ResearchTray.tsx, frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx, frontend/src/components/layout/SideNavBar/SideNavbar.tsx, frontend/src/components/layout/SideNavBar/SideTray.tsx, frontend/src/components/layout/index.ts
=> Added research side tray

frontend/src/features/mapSideBar/MapSideBarContainer.test.tsx, frontend/src/features/mapSideBar/MapSideBarContainer.tsx, frontend/src/features/mapSideBar/MapSideBarHeader.test.tsx, frontend/src/features/mapSideBar/MapSlideBarHeader.tsx, frontend/src/features/mapSideBar/__snapshots__/MapSideBarHeader.test.tsx.snap, frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts, frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx, frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.test.tsx, frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.helpers.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.tsx, frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Map layers are now properly queried after API returns property info object
=> PSP-3188 Fix property information slide-out

frontend/src/assets/scss/_variables.module.scss, frontend/src/assets/scss/colors.scss, frontend/src/components/common/form/Button.scss, frontend/src/components/maps/leaflet/LayerPopup/LayerPopup.tsx, frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx, frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.tsx, frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupLinks.test.tsx.snap, frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
Fixes for:
- PSP-3190 FT: Colors displayed on new pop-up are not the ones described on Mockup description
- PSP-3194 FT: Owner type missing
=> Map popup fixes

backend/ltsa/LtsaService.cs, backend/ltsa/Models/AssociatedPlan.cs, backend/ltsa/Models/BillingInfo.cs, backend/ltsa/Models/CanadianProvince.cs, backend/ltsa/Models/ChargeOnTitle.cs, backend/ltsa/Models/ChargeOwnershipGroup.cs, backend/ltsa/Models/ChargesOnStrataCommonProperty.cs, backend/ltsa/Models/DescriptionOfLand.cs, backend/ltsa/Models/DocOrPlanSummary.cs, backend/ltsa/Models/LandTitleDistrict.cs, backend/ltsa/Models/LandTitleDistrictCode.cs, backend/ltsa/Models/LegalNotationsOnStrataCommonProperty.cs, backend/ltsa/Models/OrderParent.cs, backend/ltsa/Models/OrderStatus.cs, backend/ltsa/Models/OwnerAddress.cs, backend/ltsa/Models/ParcelInfo.cs, backend/ltsa/Models/Title.cs, backend/ltsa/Models/TitleSummary.cs, backend/ltsa/Pims.Ltsa.csproj
-Enums now ignore non-existent values, such as "" or null.
=> psp-3164 correct unhandled pid(s) within ltsa.

backend/api/Areas/Leases/Mapping/Lease/TenantMap.cs, backend/entities/Lease.cs, frontend/src/features/leases/context/LeaseContext.tsx, frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx, frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx, frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap, frontend/src/features/leases/leaseUtils.ts, frontend/src/hooks/pims-api/useApiRequestWrapper.ts, frontend/src/interfaces/ITenant.ts
Also update backend/frontend logic to prevent organization and person information from being filled out simultaneously on lease tenants.
=> Psp 3253 prevent lease tenants from being created with org and person information

frontend/src/features/contacts/contactUtils.ts, frontend/src/features/properties/list/columns.tsx
based on the is26 db migration, ensure that frontend handles nullable address properly.
=> prevent NPE when property address is null.

frontend/src/hooks/pims-api/useApiRequestWrapper.ts
addresses:
https://sonarqube-3cd915-tools.apps.silver.devops.gov.bc.ca/project/issues?id=21faa627-fe70-4a67-89e3-1262a32d2e2c&open=AYCIhANa97oJRVKEM9n5&resolved=false&sinceLeakPeriod=true&types=BUG
=> correct sonarqube bug.

backend/api/Models/Concepts/ResearchFile/ResearchFileMap.cs, frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.test.tsx, frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx, frontend/src/features/leases/reports/aggregated/__snapshots__/ExportAggregatedLeasesContainer.test.tsx.snap, frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
PreserveReference was set at the PropertyResearchFile level but not at the ResearchFile level.
=> prevent circular references in the research file.

backend/api/Models/Concepts/ResearchFile/ResearchFilePropertyMap.cs
@FuriousLlama please review. I'm assuming that this was not intentional but want to make sure that this change wont break anything else.
=> Add missing line so that Property gets mapped. fixes psp-3449

etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
Looks like a merge corrupted this etl, rolling back to the last known good version.
=> Correct LISDB etl.

backend/api/Areas/Property/Mapping/Property/AssociationMap.cs
=> Updated research filename showing on PIMS files

backend/dal/Helpers/Extensions/LeaseExtensions.cs, frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.test.tsx, frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx, frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap, frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
- Added a custom method in LeaseExtensions.cs to map the model sort fields to entity soft fields
- Enabled sorting in the LeaseSearchResults.tsx for required columns and updated the UTs to pass according to change
=> feat(PSP-3230): Changes to enable sorting on the Lease Result table

backend/api/Areas/Property/Mapping/Property/PropertyMap.cs, backend/api/Areas/Property/Models/Property/PropertyModel.cs, backend/api/Mapping/Lookup/LookupMap.cs, frontend/src/constants/API.ts, frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts, frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.helpers.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap, frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap, frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap, frontend/src/interfaces/IPropertyApiModel.ts
=> Updated property update to have selects for region and districtg

frontend/src/components/common/TabView.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap, frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx, frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap, frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap, frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap, frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap, frontend/src/features/properties/selector/__snapshots__/MapSelectorContainer.test.tsx.snap
=> PSP-3619 Fix capitalization, PSP-3616 Fix spinner

frontend/src/features/mapSideBar/MotiInventoryContainer.tsx, frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
=> Added checks to prevent tab to show if property is not in the DB

etl/LISOS_PIMS/LISOS_22March/LISOS_22March.dtproj
ensure that the person that gets added from the tenant_contact_name in the LISOS gets added as a primary contact to the LEASE_TENANT
=> psp-3434 primary contact for organizations.

backend/api/Pims.Api.csproj, frontend/package.json, frontend/src/features/admin/edit-user/EditUserForm.tsx
(ensures that system admin option displayed on user management page).
=> cherry pick system admin fix into master branch

frontend/src/features/properties/map/research/add/AddResearchFileYupSchema.ts, frontend/src/features/properties/map/research/add/AddResearchForm.test.tsx, frontend/src/features/properties/map/research/add/AddResearchForm.tsx, frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap, frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap, frontend/src/features/properties/map/research/update/UpdateResearchFileYupSchema.ts, frontend/src/features/properties/map/research/update/properties/UpdateProperties.tsx, frontend/src/features/properties/map/research/update/properties/UpdatePropertiesYupSchema.ts, frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.tsx, frontend/src/features/properties/map/research/update/property/UpdatePropertyView.tsx, frontend/src/features/properties/map/research/update/property/UpdatePropertyYupSchema.ts, frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap, frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.test.tsx, frontend/src/utils/test-utils.tsx
=> Bug Fixes - PSP-3869, PSP-3895

frontend/src/features/admin/edit-user/EditUserForm.test.tsx, frontend/src/features/admin/edit-user/EditUserPage.test.tsx, frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap, frontend/src/features/leases/add/AddLeaseYupSchema.ts, frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositForm.test.tsx, frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositYupSchema.tsx, frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsYupSchema.ts, frontend/src/features/leases/detail/LeasePages/insurance/edit/EditContainer.tsx, frontend/src/features/leases/detail/LeasePages/insurance/edit/InsuranceForm.tsx, frontend/src/features/leases/detail/LeasePages/insurance/edit/InsuranceYupSchema.ts, frontend/src/utils/YupSchema.ts
=> Bug Fixes - PSP-3863, PSP-3865, PSP-3866, PSP-3868

frontend/src/AppRouter.tsx, frontend/src/features/properties/map/research/detail/ResearchSummaryView.test.tsx, frontend/src/features/properties/map/research/detail/ResearchSummaryView.tsx, frontend/src/features/properties/map/research/detail/__snapshots__/ResearchSummaryView.test.tsx.snap
correct handling of permissions in research file and lease and license details.
=> psp-3777 and psp-3784

backend/api/Pims.Api.csproj, frontend/package.json
Bumping to align with 2.1 release
=> Bump version on TEST

backend/api/Areas/Documents/DocumentController.cs, backend/api/Models/Concepts/Document/DocumentMap.cs, backend/api/Models/Concepts/Document/DocumentRelationshipMap.cs, backend/api/Repositories/Mayan/IEdmsDocumentRepository.cs, backend/api/Repositories/Mayan/MayanDocumentRepository.cs, backend/api/Services/DocumentService.cs, backend/api/Services/IDocumentService.cs, backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs, backend/dal/Repositories/DocumentActivityRepository.cs, backend/dal/Repositories/DocumentRepository.cs, backend/dal/Repositories/Interfaces/IDocumentActivityRepository.cs, backend/dal/Repositories/Interfaces/IDocumentRepository.cs, backend/entities/Partials/Document.cs, frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx, frontend/src/features/documents/documentDetail/DocumentDetailModal.tsx, frontend/src/features/documents/documentDetail/DocumentDetailView.tsx, frontend/src/features/documents/hooks/useDocumentRelationshipProvider.ts, frontend/src/features/documents/list/DocumentListContainer.tsx, frontend/src/features/documents/list/DocumentListView.test.tsx, frontend/src/features/documents/list/DocumentListView.tsx, frontend/src/features/documents/list/DocumentResults/DocumentResultsColumns.tsx, frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap, frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap, frontend/src/hooks/pims-api/useApiDocuments.ts
=> Delete document action | Features/psp 3799

backend/dal/Repositories/ResearchFilePropertyRepository.cs, backend/tests/unit/dal/Repositories/ResearchFilePropertyRepositoryTest.cs, backend/tests/unit/dal/Services/ResearchServiceTest.cs
association to property research purpose was causing the error. I've added manual delete logic to handle this case.
=> Psp 3964 unable to delete a property on a research file

frontend/src/features/notes/add/AddNotesContainer.test.tsx, frontend/src/features/notes/add/AddNotesContainer.tsx, frontend/src/features/notes/add/AddNotesFormModal.test.tsx, frontend/src/features/notes/add/AddNotesFormModal.tsx, frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap, frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap, frontend/src/features/notes/update/UpdateNoteContainer.tsx, frontend/src/features/notes/update/UpdateNoteFormModal.tsx
=> PSP-4034 BUGFIX - Show confirmation on cancel for Add Notes

backend/api/Pims.Api.csproj, etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx, etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj, frontend/package.json
Correct an issue introduced by adding insurance processing to the LIS_DB etl where the source query was hardcoded to LIS_DEV.
=> correct hardcoded query.

backend/api/Pims.Api.csproj, frontend/package.json, frontend/src/components/Table/Table.tsx, frontend/src/components/common/form/TableSelect.tsx
=> HOTFIX: PSP-4092 Page-to-page function missing

.github/workflows/ci-cd-pims-master.yml, .github/workflows/deploy-prod-end.yml, .github/workflows/depoy-prod-start.yml, backend/api/Pims.Api.csproj, frontend/package.json, maintenance/maintenance.sh
pims production deployment git action(s)
=> HOTFIX: Psp 3983

etl/LISOS_PIMS/LISOS_22March.sln, etl/LISOS_PIMS/LISOS_22March/LISOS_22March.dtproj
=> Psp 3928 lisos

frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx, frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx, frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap, frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.test.tsx, frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.tsx, frontend/src/features/properties/map/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap, frontend/src/mocks/mockAcquisitionFiles.ts
=> PSP-3362 Acquisition file header

frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.test.tsx, frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.tsx, frontend/src/features/properties/map/research/FormKeys.ts, frontend/src/features/properties/map/research/ResearchContainer.tsx, frontend/src/features/properties/map/research/ResearchTabsContainer.tsx, frontend/src/features/properties/map/research/ViewSelector.tsx, frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
=> PSP-4043 fix

backend/api/Pims.Api.csproj, frontend/package.json, frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx, frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx, frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
Didn't understand the scope of this issue originally. This ensures that both the display and the database of the primary contact are consistent.
=> HOTFIX: Psp-4179

backend/dal.keycloak/Partials/PimsKeycloakUserService.cs, backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
Finally tracked this down, this is why we need to get a better handle on our to-dos
=> correct issue with realm admin group being removed from kc.

backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs, backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePropertyMap.cs
This mappings were not available on DB schema last sprint. They are now in IS36
=> Add missing mappings from last sprint

frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx, frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
Issue caused by new usage of pims boundary layer, that layer requires authentication in our non-local environments (this was the cause of the 302 not the change to the FA layer).
=> correct issue with not being able to click map properties in test/dev

frontend/src/features/contacts/contact/create/validation.ts
=> Added comment section validation for Contact form

frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
=> PSP-4552: Fix input field width in Acquisition File update form

frontend/src/components/maps/leaflet/Map.tsx, frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
remove negative margin allowing filter bar to exceed size of parent.
=> psp-4485 fix mapview scroll bar

source/backend/api/Services/AcquisitionFileService.cs, source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs, source/backend/dal/Repositories/AcquisitionFileRepository.cs, source/backend/dal/Repositories/Interfaces/ISequenceRepository.cs, source/backend/dal/Repositories/SequenceRepository.cs, source/backend/tests/unit/dal/Repositories/AcquisitionRepositoryTest.cs
Also, PSP-4508 Remove unnecessary code when creating ACQ File
=> PSP-4413 Acquisition file number create and update

backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs, backend/dal/Repositories/AcquisitionFilePropertyRepository.cs, frontend/src/components/common/GenericModal.tsx, frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.test.tsx, frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.tsx, frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityPropertyModal.test.tsx.snap
=> Bug Fixes: PSP-4496, PSP-4605

.github/workflows/release.yml, Makefile
Please note this PR is against the **master** branch so it can be ready and working for our next release. I tested the github action on my fork and it ran successfully.
I don't think this PR warrants an increment in the hotfix version as there are no code changes, only devops automations.
=> PSP-4100 Fix GitHub action for releases

tools/keycloak/sync/appsettings.test.json, tools/keycloak/sync/realm.test.json
now that test is hosted in the dev.oidc keycloak, update relevant settings to point to the updated location.
=> correct test api/keycloak settings.

source/frontend/src/features/notes/detail/NoteDetailsFormModal.test.tsx, source/frontend/src/features/notes/detail/NoteDetailsFormModal.tsx
=> PSP-4702 Hide last updated info for system-generated notes

source/frontend/src/features/mapSideBar/MotiInventoryHeader.tsx, source/frontend/src/features/mapSideBar/tabs/bcAssessment/BcAssessmentTabView.tsx, source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx, source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx, source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap, source/frontend/src/mocks/mockAddress.ts, source/frontend/src/utils/propertyUtils.ts
=> PSP-5027 View property attribute - address

source/backend/api/Services/DocumentSyncService.cs, source/frontend/package-lock.json
looks like a known issue with override was preventing some versions from being applied properly. I've regenerated the package lock as suggested and that seems to have resolved the issue.
=> regenerate package-lock

source/backend/api/Models/Concepts/Lease/PropertyLeaseMap.cs, source/backend/api/Models/Concepts/Lease/PropertyLeaseModel.cs, source/frontend/src/components/propertySelector/MapSelectorContainer.tsx, source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx, source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap, source/frontend/src/features/leases/models.ts, source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx, source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/SelectedPropertyRow.tsx, source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap, source/frontend/src/models/api/PropertyLease.ts
=> PSP-4878 Add Property Picker to Lease and License update form

source/backend/tests/unit/api/Services/DocumentServiceTest.cs
- Added unit tests for Document Service
=> PSP-5154 : Increase test coverage for mayan service

source/backend/api/Controllers/LookupController.cs
=> PSP-4709 : Project Search and List view (Manage projects)

source/backend/api/Areas/Projects/Controllers/ProjectController.cs, source/backend/api/Services/IProjectService.cs, source/backend/api/Services/ProjectService.cs, source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs, source/backend/dal/Repositories/AcquisitionFileRepository.cs, source/backend/dal/Repositories/Interfaces/IProductRepository.cs, source/backend/dal/Repositories/ProductRepository.cs, source/frontend/src/components/common/form/AsyncTypeahead.tsx, source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx, source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/add/models.ts, source/frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.tsx, source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx, source/frontend/src/features/properties/map/acquisition/update/summary/models.ts, source/frontend/src/hooks/pims-api/useApiProjects.ts, source/frontend/src/hooks/providers/useProjectProvider.ts
Added functionality to update and see project's products in an acquisition file
=> Producs & Acqisition files | PSP-5213

source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
=> Fixed mesage

source/frontend/src/features/properties/map/project/add/AddProjectFileYupSchema.ts, source/frontend/src/features/properties/map/project/add/AddProjectForm.tsx, source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap, source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
- Update required fields after DB fixes
=> PSP-4514 : Create Project

source/frontend/src/components/maps/hooks/useMapSearch.tsx, source/frontend/src/features/documents/ComposedDocument.ts, source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
fixes map spinner not displaying.
=> psp-5448 re-add missing loading flag to properties load.

source/backend/api/Services/ProjectService.cs, source/backend/dal/Repositories/Interfaces/IProjectRepository.cs, source/backend/dal/Repositories/ProjectRepository.cs, source/backend/tests/unit/api/Services/ProjectServiceTest.cs, source/frontend/src/features/admin/financial-codes/list/FinancialCodeResults/FinancialCodeResults.tsx
- PSP-5364: Financial Code List - page size selector not shown
- PSP-5370: Limit project selection to regions associated to current user
=> Bug fixes: PSP-5354, PSP-5370

source/frontend/src/features/properties/map/research/add/AddResearchForm.tsx, source/frontend/src/features/properties/map/research/add/ResearchProperties.tsx, source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap, source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap, source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
=> PSP-4049: Create research file - style fixes

source/backend/api/Areas/Projects/Controllers/ProjectController.cs, source/backend/api/Services/ProjectService.cs, source/backend/dal/Repositories/Interfaces/IProductRepository.cs, source/backend/dal/Repositories/ProductRepository.cs, source/backend/tests/unit/api/Controllers/Projects/ProjectControllerTest.cs, source/backend/tests/unit/api/Services/ProjectServiceTest.cs, source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.test.tsx, source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.tsx
a duplicate product is a product with the same code and description as another product.
=> Psp 5389 - duplicate products

source/backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs, source/backend/api/Areas/Leases/Models/Lease/LeaseModel.cs, source/backend/api/Models/Concepts/Lease/LeaseMap.cs, source/backend/api/Models/Concepts/Lease/LeaseModel.cs, source/backend/dal/Repositories/LeaseRepository.cs, source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx, source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx, source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap, source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/LeasePageForm.tsx, source/frontend/src/features/leases/detail/LeasePages/details/DetailTermInformation.test.tsx, source/frontend/src/features/leases/detail/LeasePages/details/DetailTermInformation.tsx, source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx, source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/improvements/Improvements.tsx, source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.tsx, source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/ImprovementsContainer.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/improvements/styles.ts, source/frontend/src/features/leases/detail/LeasePages/insurance/details/Insurance.tsx, source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/tenant/ViewTenantForm.tsx, source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap, source/frontend/src/features/leases/models.ts, source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx, source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx, source/frontend/src/interfaces/ILease.ts, source/frontend/src/models/api/Lease.ts
=> PSP-5050 Lease file - add/update/view project details

source/backend/api/Helpers/Healthchecks/PimsDatabaseHealtcheck.cs, source/backend/api/Startup.cs
Added HealthCheck for Database Collation to an expected value for String Comparison purposes.
=> PSP-2194 : SPIKE: Specify string culture

source/frontend/src/features/documents/ComposedDocument.ts, source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx, source/frontend/src/features/documents/documentDetail/DocumentDetailForm.test.tsx, source/frontend/src/features/documents/documentDetail/DocumentDetailForm.tsx, source/frontend/src/features/documents/documentDetail/DocumentDetailHeader.tsx, source/frontend/src/features/documents/documentDetail/DocumentDetailView.test.tsx, source/frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
Think I finally sorted this one out.
=> psp-5457 update document type naming.

source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
…on state changes caused this.
=> correct inaccurate duplicate property warning.

source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx, source/frontend/src/features/properties/map/project/add/ProductsArrayForm.tsx, source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
=> PSP-5807 Move delete product button to the top of each section

source/frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx, source/frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx, source/frontend/src/features/contacts/contact/create/components/address/Address.tsx, source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.test.tsx, source/frontend/src/features/contacts/contactUtils.test.ts, source/frontend/src/features/contacts/contactUtils.ts, source/frontend/src/features/properties/map/acquisition/common/models.ts, source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx, source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap, source/frontend/src/features/properties/map/project/add/AddProjectFileYupSchema.ts, source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx, source/frontend/src/features/properties/map/project/add/AddProjectForm.tsx, source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap, source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap, source/frontend/src/features/properties/map/project/hooks/useAddProjectFormManagement.tsx, source/frontend/src/features/properties/map/project/models.ts, source/frontend/src/hooks/useCounter.ts
PSP-5863
PSP-5794
PSP-4486
PSP-5821
=> HOTFIX: Is49 fixes

source/frontend/src/components/common/form/UserRegionSelect/UserRegionSelectContainer.tsx, source/frontend/src/components/common/form/UserRegionSelect/__snapshots__/UserRegionSelectContainer.test.tsx.snap, source/frontend/src/features/projects/list/ProjectFilter/ProjectFilter.test.tsx, source/frontend/src/features/projects/list/ProjectFilter/ProjectFilter.tsx, source/frontend/src/features/projects/list/ProjectFilter/__snapshots__/ProjectFilter.test.tsx.snap, source/frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap, source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap, source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
replace project list view region filter with the one that uses the user's region.
=> Psp-5800 replace project region filter.

source/backend/api/Models/BaseModel.cs, source/backend/api/Models/Concepts/Project/ProjectModel.cs, source/backend/api/Services/FinancialCodeService.cs, source/backend/api/Services/IOrganizationService.cs, source/backend/api/Services/IPersonService.cs, source/backend/api/Services/IResearchFileService.cs, source/backend/api/Services/NoteService.cs, source/backend/api/Services/OrganizationService.cs, source/backend/api/Services/PersonService.cs, source/backend/api/Services/ResearchFileService.cs, source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs, source/backend/dal/Repositories/LeaseRepository.cs
Make Rowversion, Project id fields nullable on backend.
=> make project id, rowversion fields nullable on backend.

source/backend/api/Services/DocumentGenerationService.cs, source/backend/dal/Repositories/AcquisitionFileRepository.cs, source/backend/dal/Repositories/PropertyRepository.cs, source/database/mssql/scripts/dbscripts/PSP_PIMS_S51_00/Alter Down/123_DML_PIMS_FORM_TYPE.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_S51_00/Alter Up/123_DML_PIMS_FORM_TYPE.sql, source/frontend/src/features/documents/hooks/useDocumentGenerationRepository.ts, source/frontend/src/features/mapSideBar/layout/FileLayout.tsx, source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx, source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx, source/frontend/src/features/properties/map/acquisition/AcquisitionView.test.tsx, source/frontend/src/features/properties/map/acquisition/AcquisitionView.tsx, source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionView.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/common/AcquisitionMenu.test.tsx, source/frontend/src/features/properties/map/acquisition/common/AcquisitionMenu.tsx, source/frontend/src/features/properties/map/research/__snapshots__/ResearchContainer.test.tsx.snap, source/frontend/src/hooks/pims-api/useApiContacts.ts, source/frontend/src/hooks/useGenerateLetter.test.tsx, source/frontend/src/hooks/useGenerateLetter.ts, source/frontend/src/mocks/mockContacts.ts, source/frontend/src/models/generate/GenerateAddress.test.ts, source/frontend/src/models/generate/GenerateAddress.ts, source/frontend/src/models/generate/GenerateFile.ts, source/frontend/src/models/generate/GenerateLetter.ts, source/frontend/src/models/generate/GenerateOwner.test.ts, source/frontend/src/models/generate/GenerateOwner.ts, source/frontend/src/models/generate/GeneratePerson.test.ts, source/frontend/src/models/generate/GeneratePerson.ts, source/frontend/src/models/generate/GenerateProperty.ts
I don't think it would be appropriate to include the templates in the repo, so I'm going to attach the actual (functional) template to confluence.
=> Psp 5880 - generate letter

source/backend/api/Services/ResearchFileService.cs, source/backend/tests/core/PrincipalHelper.cs, source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
=> Added note logic when updating research status | PSP-5874

source/frontend/src/features/properties/map/agreement/detail/AgreementView.tsx
=> Added text to match mockup | psp-5992

source/backend/api/Areas/Keycloak/Mapping/AccessRequest/AccessRequestUserMap.cs, source/backend/api/Areas/Keycloak/Models/AccessRequest/UserModel.cs, source/backend/api/Models/Concepts/User/UserMap.cs, source/backend/api/Models/Concepts/User/UserModel.cs, source/backend/dal/Repositories/AccessRequestRepository.cs, source/backend/entities/Partials/UserType.cs, source/frontend/src/features/admin/access-request/AccessRequestForm.tsx, source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestContainer.test.tsx.snap, source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestForm.test.tsx.snap, source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.test.tsx.snap, source/frontend/src/features/admin/access-request/models.ts, source/frontend/src/features/admin/edit-user/EditUserContainer.tsx, source/frontend/src/features/admin/users/models.ts, source/frontend/src/mocks/accessRequestMock.ts, source/frontend/src/mocks/userMock.ts, source/frontend/src/models/api/User.ts, source/frontend/src/utils/YupSchema.ts
=> PSP-5713 : Access request - individual can Identify themselves as internal staff/contractors

source/frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx, source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap, source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx, source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
Removed the horizontal scroller from the contact list as it was unnecessary.
=> psp-5752 remove contact list horizontal scroller

source/frontend/src/components/common/form/Check.tsx, source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermForm.tsx, source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermForm.test.tsx.snap
Changing Check element values logic to be one different from the other in order to use these values for automation purposes
=> Automation - Changing Check element values

source/backend/api/Models/Concepts/Property/PropertyMap.cs, source/backend/api/Models/Concepts/Property/PropertyModel.cs, source/frontend/package.json, source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx, source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap, source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx, source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap, source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts, source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/validation.ts, source/frontend/src/models/api/Property.ts
=> Added Property General Location

source/frontend/src/features/properties/map/agreement/update/AgreementSubForm.tsx, source/frontend/src/features/properties/map/agreement/update/UpdateAgreementsYupSchema.ts, source/frontend/src/features/properties/map/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
=> PSP-6159 : BVT: Field label is missing the 'days' tag prior to Save

source/frontend/src/features/leases/add/AddLeaseContainer.tsx, source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap, source/frontend/src/features/properties/map/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap, source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap, source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap, source/frontend/src/features/properties/map/shared/SidebarFooter.tsx, source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
If the code and logic looks good, I can implement this change in all places the SideBarFooter component is used and push my branch again so every form with required fields would display an error message if the save button is pressed while those fields are missing.
=> psp-6119 display error message when required fields missing

source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs, source/backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs, source/backend/api/Models/Concepts/Property/PropertyMap.cs, source/backend/api/Models/Concepts/Property/PropertyModel.cs, source/backend/api/Models/ErrorResponseModel.cs, source/backend/api/Services/AcquisitionFileService.cs, source/backend/api/Services/IAcquisitionFileService.cs, source/backend/dal/Exceptions/UserOverrideException.cs, source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs, source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs, source/backend/dal/Repositories/PropertyRepository.cs, source/backend/tests/unit/api/Controllers/Acquisition/AcquisitionControllerTest.cs, source/backend/tests/unit/api/Routes/Acquisition/AcquisitionControllerTest.cs, source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs, source/frontend/src/features/properties/map/acquisition/ViewSelector.tsx, source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionContainer.test.tsx, source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionContainer.tsx, source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx, source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx, source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts, source/frontend/src/hooks/repositories/useAcquisitionProvider.ts, source/frontend/src/interfaces/IApiError.ts, source/frontend/src/mocks/index.mock.ts
=> PSP-6111 Transfer properties of interest to core inventory when Acquisition File is complete

source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.test.tsx, source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.tsx, source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/ImprovementsContainer.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
Changed the format of the message displayed under the improvements tab when no improvements have been added. Also put placeholder text in the description text field for every type of improvement.
=> psp-6121 UI/UX enhancements to improvements tab

source/backend/api/Controllers/LookupController.cs, source/backend/api/Models/Concepts/Take/TakeMap.cs, source/backend/api/Models/Concepts/Take/TakeModel.cs, source/backend/dal/Repositories/Interfaces/ILookupRepository.cs, source/backend/dal/Repositories/LookupRepository.cs, source/backend/dal/Repositories/TakeRepository.cs, source/backend/entities/Partials/LandActType.cs, source/backend/entities/PimsBaseContext.cs, source/frontend/src/constants/API.ts, source/frontend/src/features/mapSideBar/tabs/takes/detail/TakesDetailView.test.tsx, source/frontend/src/features/mapSideBar/tabs/takes/detail/TakesDetailView.tsx, source/frontend/src/features/mapSideBar/tabs/takes/update/TakeSubForm.tsx, source/frontend/src/features/mapSideBar/tabs/takes/update/TakesUpdateForm.tsx, source/frontend/src/features/mapSideBar/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap, source/frontend/src/features/mapSideBar/tabs/takes/update/models.ts, source/frontend/src/mocks/takes.mock.ts, source/frontend/src/models/api/Take.ts
The select field was moved above the area and end date fields per dev's request.
=> psp-6106 modify land act description field in takes to be select

source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs, source/backend/api/Services/CompensationRequisitionService.cs, source/backend/api/Services/ICompensationRequisitionService.cs, source/backend/dal/Repositories/CompensationRequisitionRepository.cs, source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs, source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailContainer.tsx, source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx, source/frontend/src/features/properties/map/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap, source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts, source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts, source/frontend/src/models/api/CompensationPayee.ts
=> PSP-5952 : View H120 Details (Compensation Requisition)

source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_SET_ALL_USERS_TO_MINISTRY.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_S55_00/Alter Up/999_DML_SET_ALL_USERS_TO_MINISTRY.sql
Added Alter Up/999_DML_SET_ALL_USERS_TO_MINISTRY.sql
=> Set All Users to Ministry Staff

source/frontend/src/components/common/List/SelectInput.tsx, source/frontend/src/components/common/form/Input.tsx, source/frontend/src/components/common/form/InputGroup.tsx, source/frontend/src/components/maps/hooks/useMapSearch.tsx, source/frontend/src/components/maps/leaflet/Map.tsx, source/frontend/src/components/maps/leaflet/mapUtils.test.tsx, source/frontend/src/components/maps/leaflet/mapUtils.tsx, source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap, source/frontend/src/components/propertySelector/search/LayerFilter.tsx, source/frontend/src/components/propertySelector/search/__snapshots__/LayerFilter.test.tsx.snap, source/frontend/src/components/propertySelector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap, source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap, source/frontend/src/features/properties/filter/PropertyFilter.tsx, source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap, source/frontend/src/features/properties/map/hooks/useMapProperties.tsx, source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap, source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap, source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap, source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap, source/frontend/src/hooks/pims-api/useFullyAttributedParcelMapLayer.ts, source/frontend/src/hooks/pims-api/useGeoServer.ts, source/frontend/src/hooks/pims-api/useWfsLayer.ts, source/frontend/src/hooks/useBcAssessmentLayer.ts
the two are related, as changes to how the cql build works is required to fix the issue with bc assessment lookups.
=> Psp 6404, psp-6152

source/backend/api/Services/AcquisitionFileService.cs, source/backend/dal/Repositories/InterestHolderRepository.cs, source/backend/tests/unit/dal/Repositories/InterestHolderRepositoryTest.cs, source/frontend/src/components/common/form/FastCurrencyInput.tsx, source/frontend/src/components/common/form/Select.tsx, source/frontend/src/features/properties/map/acquisition/update/stakeholders/__snapshots__/UpdateStakeHolderForm.test.tsx.snap, source/frontend/src/features/properties/map/acquisition/update/stakeholders/models.test.ts, source/frontend/src/features/properties/map/acquisition/update/stakeholders/models.ts, source/frontend/src/features/properties/map/compensation/CompensationRequisitionYupSchema.ts, source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx, source/frontend/src/features/properties/map/compensation/models.ts, source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionForm.tsx, source/frontend/src/features/properties/map/compensation/update/financials/FinancialActivitiesSubForm.tsx, source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
Prevents users with the same interest type being grouped on the edit interest holders screen.
=> psp-6386 allow interest holders to be deleted. 

.vscode/settings.json, source/frontend/src/components/common/ModalContainer.test.tsx, source/frontend/src/components/common/form/ContactInput/ContactInputView.test.tsx, source/frontend/src/components/common/form/FastDatePicker.test.tsx, source/frontend/src/components/common/form/Multiselect.test.tsx, source/frontend/src/components/common/form/NotesModal.test.tsx, source/frontend/src/components/common/form/ParentSelect.test.tsx, source/frontend/src/components/common/form/ProjectSelector/ProjectSelector.test.tsx, source/frontend/src/components/propertySelector/search/LayerFilter.test.tsx, source/frontend/src/hooks/layer-api/useLayerQuery.test.tsx
Addressing the act warnings for when the tests are run. Checked and fixed all the tests in the frontend/src/components/ folder.
=> psp-2175 fix frontend tests console output

source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_SET_LEASE_PAYMENT_STATUS_TYPE_CODE.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_S55_00/Alter Up/999_DML_SET_LEASE_PAYMENT_STATUS_TYPE_CODE.sql
Set all null lease payment statuses to their correct value based on the lease  term's payment amount + GST
=> Set Lease Payment Status

.github/workflows/keycloak-sync.yml, tools/keycloak/sync/appsettings.development.json, tools/keycloak/sync/appsettings.json
The secrets need to be added to the repository in order for the workflow to run successfully. Please check the file for how they should be named.
=> psp-6255: keycloak sync github action

etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION.sln, etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION.dtproj
=> PSP - 6414 and 6418

.github/workflows/credentials-scan.yml
* correct credentials scan failure.
* force dependency versions.
---------
=> fix trufflehog install from failing (#3333)

.github/workflows/retag-dev-to-test.yml
also remove existing test ci/cd action
=> psp-6470 - action to tag dev to test

source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.ts
missed requirement apparently.
=> psp-6820 make take area optional

source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Test Data/038_PIMS_USER.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_S61_00/Test Data/038_PIMS_USER.sql
May have been overwritten inadvertently as this file didn't exist in the LATEST folder. @FuriousLlama @dfilteau please be aware of this change to avoid future overwrites. (ie. in IS62)
=> restoring updated version of PIMS_USER seed script, overriden in IS60.

source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
=> PSP-6732 Add tooltip for alternate project

source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs, source/backend/api/Areas/Reports/Controllers/AcquisitionController.cs, source/backend/api/Areas/Reports/Models/Acquisition/AgreementReportModel.cs, source/backend/api/Areas/Reports/Models/Acquisition/CompensationFinancialReportModel.cs, source/backend/api/Areas/Reports/Models/Acquisition/CompensationFinancialReportTotalsModel.cs, source/backend/api/Services/CompReqFinancialService.cs, source/backend/api/Services/ICompReqFinancialService.cs, source/backend/dal/Repositories/AgreementRepository.cs, source/backend/dal/Repositories/CompReqFinancialRepository.cs, source/backend/dal/Repositories/Interfaces/ICompReqFinancialRepository.cs, source/backend/tests/unit/api/Models/AgreementReportModelTest.cs, source/backend/tests/unit/api/Models/CompensationFinancialReportModelTest.cs, source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs, source/backend/tests/unit/api/Services/CompReqFinancialServiceTest.cs, source/backend/tests/unit/dal/Repositories/CompReqFinancialRepositoryTest.cs, source/backend/tests/unit/dal/Repositories/H120CategoryRepositoryTest.cs, source/frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx, source/frontend/src/features/leases/detail/LeasePages/surplus/Surplus.test.tsx, source/frontend/src/features/projects/reports/ProjectExportContainer.test.tsx, source/frontend/src/features/projects/reports/ProjectExportContainer.tsx, source/frontend/src/features/projects/reports/ProjectExportForm.test.tsx, source/frontend/src/features/projects/reports/ProjectExportForm.tsx, source/frontend/src/features/projects/reports/models.ts, source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts, source/frontend/src/hooks/repositories/useAcquisitionProvider.ts, source/frontend/src/hooks/util/useApiRequestWrapper.ts, source/frontend/src/models/api/ProjectFilter.ts, source/frontend/src/utils/utils.ts
=> PSP-6517 Compensation Requisition Export

.github/workflows/ci-cd-pims-dev.yml, .github/workflows/retag-dev-to-test.yml
=> Fix keycloak sync in github actions

etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/Integration Services Project1.dtproj, etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/Integration Services Project1.dtproj.user, etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/LIS_DB_to_PIMS_ACTIVITY_PSP_6942.dtsx, etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/LIS_DB_to_PIMS_ACTIVITY_PSP_6943.dtsx, etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/Package.dtsx
This commit is related to bring LISDB data into PIMS as per requirements mentioned in these 2 tickets - PSP-6942 and PSP-6943
=> PSP-6942 and PSP-6943

source/frontend/src/assets/scss/App.scss, source/frontend/src/assets/scss/colors.scss, source/frontend/src/components/common/GenericModal.tsx, source/frontend/src/components/common/form/NotesModal.tsx, source/frontend/src/components/common/mapFSM/useMapSearch.tsx, source/frontend/src/components/contact/ContactManagerModal.tsx, source/frontend/src/components/modals/roleMismatch.tsx, source/frontend/src/features/documents/documentDetail/DocumentDetailModal.tsx, source/frontend/src/features/documents/documentUpload/DocumentUploadModal.tsx, source/frontend/src/features/documents/list/DocumentListView.tsx, source/frontend/src/features/help/components/HelpModal.tsx, source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx, source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx, source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/GenerateLetterRecipientsModal.tsx, source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/common/modals/AcquisitionFormModal.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx, source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx, source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap, source/frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap, source/frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap, source/frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap, source/frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap, source/frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap, source/frontend/src/hooks/useApiUserOverride.ts, source/frontend/src/hooks/usePimsIdleTimer.tsx
=> PSP-6778 : Update dialog boxes

source/frontend/src/components/common/form/TypeaheadSelect.test.tsx, source/frontend/src/components/common/form/TypeaheadSelect.tsx, source/frontend/src/components/common/form/__snapshots__/TypeaheadSelect.test.tsx.snap, source/frontend/src/features/mapSideBar/project/add/AddProjectForm.test.tsx, source/frontend/src/features/mapSideBar/project/add/AddProjectForm.tsx, source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectForm.test.tsx.snap, source/frontend/src/features/mapSideBar/project/models.ts, source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/ProjectSummaryView.test.tsx, source/frontend/src/features/mapSideBar/project/tabs/projectDetails/update/UpdateProjectContainer.tsx, source/frontend/src/utils/financialCodeUtils.ts
**NOTE:** working on unit tests - will add them to the pr later
=> PSP-7157 Project dropdowns

source/backend/api/Services/AcquisitionFileService.cs, source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.test.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx, source/frontend/src/hooks/useApiUserOverride.ts, source/frontend/src/utils/axiosUtils.ts
Check for draft agreements and compensations when completing a file.
=> Agreements statuscompletition | psp-7079

source/backend/api/Pims.Api.csproj, source/backend/dal/Repositories/OrganizationRepository.cs, source/frontend/package.json, source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts, source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/models.test.ts, source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/models.ts, source/frontend/src/interfaces/IContactSearchResult.ts
see bug descriptions. contains psp-7297 and psp-7312.
=> V4.1.2 66.43 hotfix

source/backend/api/Areas/Disposition/Controllers/DispositionFileController.cs, source/backend/api/Services/DispositionFileService.cs, source/backend/api/Services/IDispositionFileService.cs, source/backend/dal/Repositories/DispositionFileRepository.cs, source/backend/dal/Repositories/Interfaces/IDispositionFileRepository.cs, source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs, source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.tsx, source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainerView.test.tsx, source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainerView.tsx, source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.test.tsx, source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.tsx, source/frontend/src/hooks/pims-api/useApiDispositionFile.ts, source/frontend/src/hooks/repositories/useDispositionProvider.ts
=> PSP-7363 : Delete Offer (Disposition)

etl/PIMS_HIST_LOAD/PIMS_HIST_LOAD.dtproj, etl/PIMS_HIST_LOAD/PIMS_HIST_TABLES_LOAD.dtsx, etl/PIMS_HIST_LOAD/PIMS_HIST_TABLES_LOAD_LISOS_ETL_USER.dtsx
Fix on missing Historical rows that were identified on 3 tables in UAT database
1.PIMS_INSURANCE
2.PIMS_LEASE_TENANT
3.PIMS_PROPERTY_LEASE
=> PSP-7639 PIMS HIST Table fix commit

source/backend/api/Helpers/Extensions/DispositionFileExtensions.cs, source/backend/api/Helpers/Extensions/PrincipalExtensions.cs, source/backend/api/Services/DispositionFileService.cs, source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs, source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.test.tsx, source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.tsx, source/frontend/src/utils/test-utils.tsx
=> PSP-7510 : Disallow Contractor to Remove Themself from Disposition File

source/backend/dal/Repositories/PropertyLeaseRepository.cs, source/frontend/src/features/leases/detail/LeasePages/AddressSubForm.test.tsx, source/frontend/src/features/leases/detail/LeasePages/AddressSubForm.tsx, source/frontend/src/features/leases/detail/LeasePages/__snapshots__/AddressSubForm.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.test.tsx
NOTE: this file is not in our current format and should be updated to conform, but that is outside the scope of this change.
=> psp-7679 display lease province and country

source/backend/api/Services/DispositionFileService.cs, source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
=> PSP-7722 BVT. Disposition File: System is not displaying warning message when the status is moved from non-editable state(Cancelled)

source/backend/api/Areas/Disposition/Controllers/DispositionFileController.cs, source/backend/api/Helpers/Extensions/PrincipalExtensions.cs, source/backend/api/Services/DispositionFileService.cs, source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFilePropertyModel.cs, source/backend/apimodels/Models/Concepts/Property/PropertyMap.cs, source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs, source/backend/dal/Repositories/PropertyRepository.cs, source/backend/tests/core/Entities/PropertyHelper.cs, source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs, source/frontend/src/features/mapSideBar/disposition/DispositionContainer.test.tsx, source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx, source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx, source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx, source/frontend/src/features/mapSideBar/disposition/models/AddDispositionFormYupSchema.ts, source/frontend/src/features/mapSideBar/disposition/models/DispositionFormModel.ts, source/frontend/src/hooks/useApiUserOverride.ts
Also, prevent user from adding properties outside of their assigned regions:
=> PSP-7547 Auto-select region for disposition file

source/backend/dal/Models/PropertyFilterCriteria.cs, source/backend/dal/Repositories/PropertyRepository.cs, source/backend/tests/core/Entities/PropertyHelper.cs, source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs, source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx, source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts, source/frontend/src/components/common/mapFSM/machineDefinition/types.ts, source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx, source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx, source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/models.ts, source/frontend/src/components/maps/leaflet/Layers/util.tsx, source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx, source/frontend/src/mocks/mapFSM.mock.ts, source/frontend/src/models/api/ProjectFilterCriteria.ts, source/frontend/src/models/layers/pimsPropertyLocationView.ts, source/frontend/src/react-app-env.d.ts
=> PSP-7655 advanced map filter for property ownership

Makefile, docker-compose.yml, openshift/4.0/templates/sysdig/sysdig-team.yaml, source/backend/api/Pims.Api.csproj, source/backend/api/Startup.cs, tools/prometheus/prometheus.yml
Initial PR to start collecting metrics at our api level
=> PSP-7636 Prometheus/Sysdig metrics

source/backend/api/Pims.Api.csproj, source/backend/dal/Repositories/UserRepository.cs, source/frontend/package-lock.json, source/frontend/package.json, source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/AgreementSubForm.tsx, source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
ensure property updates propagate without refresh.
Always display export as if page 1 was selected.
=> Release 5.0 hotfix 1

source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx, source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
=> Fix "retired" label on property information header

source/backend/api/Services/DocumentFileService.cs, source/backend/api/Services/DocumentService.cs, source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
=> PSP-6765 empty file upload error

Makefile, docker-compose.yml, source/backend/Dockerfile, source/frontend/Dockerfile, source/frontend/Makefile, tools/mayan-edms/docker-compose.yml
Fix dockerfiles so that they are compatible with version bumps. add profiles to services.
update makefiles with above profile changes.
=> update docker-compose so primary docker compose refers to mayan.

etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE.dtproj, etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE.dtproj.user, etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE.dtsx, etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE.sln, etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE_UPD.dtproj.user, etl/PIMS_PROPERTY_MERGE_UPD/Project.params
ETL Files to dedupe PIMS PROPERTY table and update its relationship tables.
Jira ticket - https://jira.th.gov.bc.ca/browse/PSP-7482
Confluence - https://confluence.th.gov.bc.ca/x/wYNSCw
=> PIMS PROPERTY ETL Merge files commit

source/backend/api/Pims.Api.csproj, source/backend/apimodels/Models/Concepts/Property/PolygonMap.cs, source/frontend/package.json, source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx, source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx, source/frontend/src/utils/mapPropertyUtils.ts, source/frontend/src/utils/utils.ts
=> Hotfix 5.1.2

.github/workflows/app-react.yml, source/frontend/package-lock.json, source/frontend/package.json, source/frontend/public/mockServiceWorker.js, source/frontend/src/AppRouter.test.tsx, source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.test.tsx, source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx, source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx, source/frontend/src/features/mapSideBar/project/common/ProjectHeader.test.tsx, source/frontend/src/mocks/msw/browser.ts, source/frontend/src/mocks/msw/handlers.ts, source/frontend/src/mocks/msw/server.ts, source/frontend/src/setupTests.ts
fixed issue where unhandled requests not being caught by msw
updated msw
incremented number of workers in gha
fixed unhandled requests.
updated approuter tests to promote stability.
=> unit test stability corrections

source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
https://github.com/bcgov/PSP/assets/24322224/f0f1c321-4ac0-41b6-9307-7a5a6dc2901b
=> PSP-8124 Fix map zoom bug for draft markers

source/backend/api/Areas/HistoricalNumber/HistoricalNumberController.cs, source/backend/api/Controllers/LookupController.cs, source/backend/api/Services/IPropertyService.cs, source/backend/api/Services/PropertyService.cs, source/backend/dal/Repositories/HistoricNumberRepository.cs, source/backend/dal/Repositories/Interfaces/IHistoricalNumberRepository.cs, source/backend/dal/Repositories/Interfaces/ILookupRepository.cs, source/backend/dal/Repositories/LookupRepository.cs, source/frontend/src/constants/API.ts, source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx, source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx, source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdateHistoricalNumbersSubForm.tsx, source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx, source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx, source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx, source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap, source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts, source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/validation.ts, source/frontend/src/features/mapSideBar/research/common/ResearchHeader.test.tsx, source/frontend/src/hooks/pims-api/useApiHistoricalNumbers.ts, source/frontend/src/hooks/repositories/useHistoricalNumberRepository.ts
=> PSP-5492 Update Historical # and Type on Property Details (Property Attributes)

source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx, source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
(zoomed out so you can see the different types).
=> psp-8108 style changes for improvements page.

source/frontend/src/components/Table/PageSizeSelector.test.tsx, source/frontend/src/components/Table/PageSizeSelector.tsx, source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap, source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap, source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap, source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap, source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap, source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap, source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap, source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap, source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap, source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap, source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap, source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
=> PSP-8587 table pagination visual bug

source/backend/api/Pims.Api.csproj, source/backend/api/Services/LeaseService.cs, source/frontend/package.json, source/frontend/src/components/Table/PageSizeSelector.test.tsx, source/frontend/src/components/Table/PageSizeSelector.tsx, source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap, source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap, source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap, source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap, source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap, source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap, source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap, source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap, source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap, source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap, source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap, source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
Also bring in git commit history that got squashed in last 5.4 merge
=> 5.4 alignment

etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.dtproj, etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.dtproj.user, etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.sln, etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS_LOAD.dtsx, etl/LISDB_PIMS_HISTORICAL_NUMBERS/Project.params
SSIS ETL Package commits for PSP-8524 changes - LIST Historical numbers ETL to PIMS
=> commits for PSP-8524 changes

source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
Also fixed "License" -> "Licence" in the section header:
=> PSP-7879 Fix label width

source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/999_PSP_PIMS_LEASE_Alter_Down.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_PSP_PIMS_LEASE_Alter_Up.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/999_PSP_PIMS_INSURANCE_Alter.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/999_PSP_PIMS_LEASE_Alter.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_S82_00/Alter Down/999_PSP_PIMS_LEASE_Alter_Down.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_S82_00/Alter Up/999_PSP_PIMS_LEASE_Alter_Up.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_S82_00/Build/999_PSP_PIMS_INSURANCE_Alter.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_S82_00/Build/999_PSP_PIMS_LEASE_Alter.sql
Change PIMS_LEASE.ORIG_START_DATE to NULL
=> IS-82.00 Modification

source/frontend/src/assets/scss/colors.scss, source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
=> PSP-8672: Disposed Property Label

source/backend/api/Pims.Api.csproj, source/backend/api/Repositories/Mayan/MayanBaseRepository.cs, source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs, source/backend/api/Services/DocumentService.cs, source/backend/tests/unit/api/Services/DocumentServiceTest.cs, source/frontend/package.json
=> Psp 5563 - correct exceptions bypassing error handling.

source/backend/api/Areas/Leases/Controllers/LeaseController.cs, source/frontend/src/features/leases/add/AddLeaseForm.tsx, source/frontend/src/features/leases/add/AddLeaseYupSchema.ts, source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx, source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx, source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap, source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap, source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx, source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx, source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx, source/frontend/src/features/leases/models.ts, source/frontend/src/mocks/lookups.mock.ts
https://github.com/bcgov/PSP/assets/24322224/285cab78-9708-41bc-9a98-36dea624e63b
=> PSP-8312 Start date not mandatory for non-active leases

.github/workflows/ci-cd-pims-dev.yml, .github/workflows/deploy-prod-start.yml, .github/workflows/retag-dev-to-test.yml, .github/workflows/retag-test-to-uat.yml
Fixing script errors in DB upgrade github action:
=> PSP-8703 Fix database upgrade GitHub action

source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx, source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx, source/frontend/src/features/mapSideBar/property/tabs/takes/detail/__snapshots__/TakesDetailView.test.tsx.snap, source/frontend/src/mocks/takes.mock.ts
=> PSP-8409 Takes UI/UX cleanup

source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx, source/frontend/src/components/propertySelector/MapSelectorContainer.tsx, source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx, source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.tsx, source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
1) enforce 15 max limit correctly
2) function correctly with no pid/pin
3) function correctly when plan number is shared.
=> psp-8690 Ensure that selected locations

source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.test.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx, source/frontend/src/hooks/useApiUserOverride.ts
=> PSP-8801 Acquisition Files - When default region is changed, the warning header is different between the create form and the edit form

etl/LISDB_PIMS_HISTORICAL_NUMBERS/FIX_LISDB_PIMS_HISTORICAL_NUMBERS_LOAD.dtsx, etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.dtproj, etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.dtproj.user
ETL Data Correction on LIS Historical numbers 
Jira Ticket - https://jira.th.gov.bc.ca/browse/PSP-8736
=> ETL Data Correction on LIS Historical numbers

source/backend/api/Pims.Api.csproj, source/backend/api/Services/DocumentService.cs, source/backend/apimodels/Models/Mayan/Document/DocumentDetailModel.cs, source/backend/apimodels/Models/Mayan/Document/DocumentTypeModel.cs, source/backend/apimodels/Models/Mayan/Document/FileLatestModel.cs
Added extra fields for the mayan models. Made some fields nullable to… match the mayan returned results
=> Fixes Mayan null pointer for Size value

source/backend/api/Services/LeaseService.cs, source/frontend/src/AppRouter.test.tsx, source/frontend/src/components/common/ExpandableTextList.test.tsx, source/frontend/src/components/propertySelector/MapSelectorContainer.tsx, source/frontend/src/components/propertySelector/selectedPropertyList/SelectedPropertyRow.test.tsx, source/frontend/src/components/propertySelector/selectedPropertyList/SelectedPropertyRow.tsx, source/frontend/src/components/propertySelector/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap, source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx, source/frontend/src/features/leases/add/AddLeaseForm.tsx, source/frontend/src/features/leases/add/AdministrationSubForm.test.tsx, source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx, source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx, source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap, source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.test.tsx, source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx, source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap, source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/SelectedPropertyRow.test.tsx, source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/SelectedPropertyRow.tsx, source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx, source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap, source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.test.tsx, source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap, source/frontend/src/features/mapSideBar/research/ResearchContainer.test.tsx, source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap, source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap, source/frontend/src/features/properties/map/MapContainer.test.tsx
=> PSP-8969 Allow for region to be auto populated when adding a property to lease/licence

source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx, source/frontend/src/features/documents/documentUpload/DocumentUploadForm.test.tsx, source/frontend/src/features/documents/documentUpload/DocumentUploadForm.tsx, source/frontend/src/features/documents/documentUpload/DocumentUploadModal.tsx, source/frontend/src/features/documents/documentUpload/__snapshots__/DocumentUploadForm.test.tsx.snap, source/frontend/src/features/documents/list/DocumentListView.test.tsx, source/frontend/src/features/documents/list/DocumentListView.tsx, source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap, source/frontend/src/features/notes/list/NoteListView.tsx, source/frontend/src/mocks/documents.mock.ts
https://github.com/user-attachments/assets/32aae819-2e2f-4980-a5b6-b60d79f54497
=> PSP-9083, PSP-9062 Document file upload fixes

source/frontend/src/features/leases/add/RenewalSubForm.tsx, source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.test.tsx, source/frontend/src/features/leases/detail/LeasePages/details/LeaseRenewalsView.test.tsx, source/frontend/src/features/leases/detail/LeasePages/details/LeaseRenewalsView.tsx, source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx, source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.test.ts
=> PSP-9065 UI cleanup

source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
=> Psp 8933 move coordinates to align with other fields

source/backend/dal.keycloak/PimsKeycloakService.cs, source/backend/dal/Repositories/AccessRequestRepository.cs, source/backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
--------
https://github.com/user-attachments/assets/b1c37dac-808e-4168-82be-646685f3f73b
=> PSP-9153 Copy access request notes to the user's notes on approval

source/backend/api/Areas/Reports/Controllers/AcquisitionController.cs, source/backend/api/Areas/Reports/Models/Acquisition/CompensationFinancialReportModel.cs, source/backend/api/Areas/Reports/Models/Acquisition/CompensationFinancialReportTotalsModel.cs, source/backend/api/Services/CompReqFinancialService.cs, source/backend/dal/Repositories/CompReqFinancialRepository.cs, source/backend/dal/Repositories/Interfaces/ICompReqFinancialRepository.cs, source/backend/tests/unit/api/Models/CompensationFinancialReportModelTest.cs, source/backend/tests/unit/api/Services/CompReqFinancialServiceTest.cs, source/backend/tests/unit/dal/Repositories/CompReqFinancialRepositoryTest.cs, source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/ConsultationListView.test.tsx, source/frontend/src/features/projects/reports/ProjectExportContainer.tsx
=> PSP-9207 L/L H120 details - need to be added to Compensation Requisition Export

source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs, source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListContainer.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListView.tsx, source/frontend/src/features/mapSideBar/shared/detail/FileTabs.tsx
=> PSP-9268 Sub-files tab skeleton view and container

source/frontend/src/components/maps/MapLeafletView.tsx
…te, prevent other fit bounds requests from being fired.
=> Psp 9347 PSP-9353 - zoom functionality not working after displaying search results.

source/frontend/src/components/common/styles.ts, source/frontend/src/components/layout/SideNavBar/AcquisitionTray.test.tsx, source/frontend/src/components/layout/SideNavBar/AcquisitionTray.tsx, source/frontend/src/components/layout/SideNavBar/AdminTools.tsx, source/frontend/src/components/layout/SideNavBar/ContactTray.tsx, source/frontend/src/components/layout/SideNavBar/DispositionTray.tsx, source/frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx, source/frontend/src/components/layout/SideNavBar/ProjectTray.tsx, source/frontend/src/components/layout/SideNavBar/ResearchTray.tsx, source/frontend/src/components/layout/SideNavBar/SideTray.tsx, source/frontend/src/components/layout/SideNavBar/SideTrayLayout.tsx, source/frontend/src/components/layout/SideNavBar/SubdCons.tsx, source/frontend/src/components/layout/SideNavBar/__snapshots__/AcquisitionTray.test.tsx.snap, source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap, source/frontend/src/components/layout/SideNavBar/styles.ts, source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap, source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap, source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap, source/frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx, source/frontend/src/features/mapSideBar/layout/__snapshots__/MapSideBarLayout.test.tsx.snap, source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap, source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap, source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
=> PSP-9351 UI/UX: The close button at the top right side of the sub-menu should be integrated within the header

source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryView.test.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryView.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/models.ts, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
=> PSP-9465 Sub interest section is missing on the view screen of Sub-interest file 

source/frontend/src/components/common/TabView.tsx, source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap, source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap, source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap, source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap, source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap, source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap, source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap, source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap, source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap, source/frontend/src/features/mapSideBar/project/tabs/__snapshots__/ProjectTabsContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap, source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap, source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap, source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
=> PSP-9205 : UI UX Clean Up - tab menu - color replacement

source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx, source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
A small bug mentioned by Praveen at the DEVs/FT chat
=> Adding tooltip of Acquisition File Create form

source/frontend/src/components/Table/Table.scss
=> PSP-9475 UI UX cleanup - sub-table expander arrow alignment

source/frontend/src/features/documents/list/DocumentListView.tsx, source/frontend/src/features/notes/list/NoteListView.tsx
=> PSP-9476: UI UX Clean Up - Documents and Notes - Buttons - add "+" 

.github/workflows/retag-dev-to-test.yml
proxy is a deployment, not a DC
=> Fix TEST deployment.

source/frontend/src/components/common/ApiVersionInfo.test.tsx, source/frontend/src/components/layout/Footer/Footer.test.tsx, source/frontend/src/components/layout/Footer/__snapshots__/Footer.test.tsx.snap, source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
https://github.com/user-attachments/assets/0e818fa4-8748-4dfa-a36d-12f2892200fe
=> PSP-9529: Fix faulty logic with retired property filter

source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx, source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts, source/frontend/src/components/common/mapFSM/machineDefinition/types.ts, source/frontend/src/components/common/mapFSM/useMapSearch.tsx, source/frontend/src/components/maps/MapLeafletView.tsx, source/frontend/src/mocks/mapFSM.mock.ts
Will work on tests later this sprint (affected code has no tests currently).
=> psp-9485 zoom map to individual results, or zoom out to multiple.

source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx, source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx, source/frontend/src/features/mapSideBar/property/__snapshots__/MotiInventoryHeader.test.tsx.snap, source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.test.tsx, source/frontend/src/mocks/data.mock.ts
=> PSP-9486 UI UX Property Information - moving PIN information to the left

source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts, source/frontend/src/components/maps/MapLeafletView.tsx
https://github.com/user-attachments/assets/f74fe16f-b9b2-4d45-b711-801f310173c1
=> PSP-9593 Fix map fit to bounds error on load

source/frontend/src/features/admin/users/ManageUsersPage.test.tsx, source/frontend/src/features/admin/users/__snapshots__/ManageUsersPage.test.tsx.snap, source/frontend/src/features/admin/users/components/UsersFilterBar.tsx
=> PSP-9517 Remove "cannot determine" region dropdown from User Management screen under Admin Tools

source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx, source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx, source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx, source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx, source/frontend/src/constants/API.ts, source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx, source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx, source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx, source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx, source/frontend/src/features/mapSideBar/router/MapRouter.tsx, source/frontend/src/hooks/repositories/useComposedProperties.ts, source/frontend/src/hooks/repositories/useMapProperties.tsx, source/frontend/src/utils/propertyUtils.ts
https://github.com/user-attachments/assets/7023593e-5ba0-4236-b43b-f010dab9b544
=> PSP-9570 Property Information leaflet should open up when a property is part of the PIMS Inventory regardless if it has a PID or not

source/backend/api/Services/DocumentQueueService.cs, source/backend/dal/PIMSContextFactory.cs, source/backend/dal/Repositories/DocumentQueueRepository.cs, source/backend/dal/Repositories/Interfaces/IDocumentQueueRepository.cs, source/backend/entities/Models/DocumentQueueSearchResult.cs, source/backend/scheduler/appsettings.json, source/backend/tests/unit/api/Services/DocumentQueueServiceTest.cs
reduce round trip to db and simplify max file length logic.
add flag to db to allow automatic retries for transitive failures.
Fix incorrect job name in appsettings.json
=> Psp 9512 - corrections/enhancements

source/backend/api/Services/AcquisitionFileService.cs, source/backend/api/Services/DispositionFileService.cs, source/backend/api/Services/LeaseService.cs, source/backend/api/Services/PropertyOperationService.cs, source/backend/api/Services/PropertyService.cs, source/backend/tests/unit/api/Services/LeaseServiceTest.cs, source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx, source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
~~Unit tests coming in another PR~~ Tests added
https://github.com/user-attachments/assets/0252939d-7a1e-4172-b3d2-2e53278e6887
=> PSP-9416 Prevent deletion of properties that have been subdivided or consolidated

source/frontend/src/features/documents/list/DocumentResults/DocumentResultsColumns.tsx
=> PSP-9772: System displays wrong icon for the view document when mouse hovered

source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx, source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
=> PSP-9799 Fix faulty logic when formatting project name and description

source/backend/api/Pims.Api.csproj, source/backend/api/Services/DocumentFileService.cs, source/backend/api/Services/DocumentService.cs, source/backend/tests/core/TestHelper.cs, source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs, source/backend/tests/unit/api/Services/DocumentServiceTest.cs, source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Build/075_DML_PIMS_ROLE_CLAIM.sql, source/frontend/package.json
Correct IS96 database build
Fix restriction on document extension no longer being applied during upload
=> HOTFIX: psp-9813, psp-9814 

source/frontend/src/components/Table/PageSizeSelector.test.tsx, source/frontend/src/components/Table/PageSizeSelector.tsx, source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap, source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap, source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap, source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap, source/frontend/src/features/admin/users/__snapshots__/ManageUsersPage.test.tsx.snap, source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap, source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap, source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap, source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap, source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap, source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap, source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap, source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/__snapshots__/PropertyContactListView.test.tsx.snap, source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
=> PSP-9825 Table Pagination bug fix

source/frontend/src/components/common/ActiveIndicator.tsx, source/frontend/src/components/common/buttons/DownloadButton.tsx, source/frontend/src/components/common/styles.ts, source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx, source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap, source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap, source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx, source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap, source/frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx, source/frontend/src/components/layout/SideNavBar/styles.ts, source/frontend/src/features/admin/users/__snapshots__/ManageUsersPage.test.tsx.snap, source/frontend/src/features/admin/users/components/UsersFilterBar.tsx, source/frontend/src/features/admin/users/constants/index.tsx, source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap, source/frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx, source/frontend/src/features/leases/reports/aggregated/__snapshots__/ExportAggregatedLeasesContainer.test.tsx.snap, source/frontend/src/features/leases/reports/payments/ExportLeasePaymentsContainer.tsx, source/frontend/src/features/leases/reports/payments/__snapshots__/ExportLeasePaymentsContainer.test.tsx.snap, source/frontend/src/features/projects/reports/ProjectExportFormContent.tsx
=> PSP-9774, PSP-8562: UI UX cleanup 

source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/075_DML_PIMS_ROLE_CLAIM.sql, source/database/mssql/scripts/dbscripts/PSP_PIMS_S98_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
DB Seed for IS98 was broken due to wrong PIMS_ROLE name reference
=> Fix DB seed  - IS 98

source/backend/Dockerfile.scheduler, source/backend/Pims.Scheduler.Test/Pims.Scheduler.Test.csproj, source/backend/Pims.Scheduler.Test/Repositories/PimsDocumentQueueRepositoryTests.cs, source/backend/Pims.Scheduler.Test/Services/DocumentQueueServiceTests.cs, source/backend/api/Areas/Documents/DocumentQueueController.cs, source/backend/api/Helpers/Extensions/DocumentUploadRequestExtension.cs, source/backend/api/Helpers/Extensions/FormFileExtensions.cs, source/backend/api/README.md, source/backend/api/Services/IDocumentQueueService.cs, source/backend/apimodels/CodeTypes/DataSourceTypes.cs, source/backend/apimodels/CodeTypes/DocumentQueueStatusTypes.cs, source/backend/apimodels/CodeTypes/DocumentStatusTypes.cs, source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileProgressStatusesMap.cs, source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileProgressStatusesModel.cs, source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileTakingStatusesMap.cs, source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileTakingStatusesModel.cs, source/backend/apimodels/Models/Concepts/DocumentQueue/DocumentQueueMap.cs, source/backend/apimodels/Models/Concepts/DocumentQueue/DocumentQueueModel.cs, source/backend/apimodels/Models/Concepts/Project/ProjectPersonMap.cs, source/backend/apimodels/Models/Concepts/Project/ProjectPersonModel.cs, source/backend/core.api/Repositories/RestCommon/IRestRespository.cs, source/backend/core.api/Services/BaseService.cs
This reverts commit 185fdc3c640b7e848571394b2f1da2edcc7447a6.
=> Revert "R5.7 ETLs"

source/backend/api/Pims.Api.csproj, source/frontend/package-lock.json, source/frontend/package.json, source/frontend/src/components/maps/MapLeafletView.tsx, source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.test.tsx, source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx, source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap, source/frontend/src/components/maps/leaflet/Layers/useConfiguredMapLayers.tsx
=> HOTFIX: PSP-9939 Layer control screen is displaying blank

source/backend/dal/Repositories/CompensationRequisitionRepository.cs, source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs, source/backend/tests/unit/dal/Repositories/CompensationRequisitionRepositoryTest.cs
https://github.com/user-attachments/assets/c8e2a674-d23f-4ea2-b18c-ebe6a8edb853
=> PSP-9095 User is not able to delete the requisition

source/backend/apimodels/Models/Concepts/CompensationRequisition/CompReqPayeeMap.cs, source/backend/apimodels/Models/Concepts/CompensationRequisition/CompReqPayeeModel.cs, source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs, source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs, source/backend/dal/Repositories/CompensationRequisitionRepository.cs, source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts, source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx, source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx, source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.tsx, source/frontend/src/features/mapSideBar/compensation/models/CompensationRequisitionFormModel.ts, source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.test.tsx, source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.tsx, source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.test.tsx, source/frontend/src/mocks/compensations.mock.ts, source/frontend/src/models/api/generated/ApiGen_Concepts_CompReqPayee.ts, source/frontend/src/models/api/generated/ApiGen_Concepts_CompensationRequisition.ts, source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.test.ts, source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
https://github.com/user-attachments/assets/314e387d-1e6f-470a-b4f7-59062379d7b4
=> PSP-9907 Support legacy payee

source/backend/api/Pims.Api.csproj, source/backend/scheduler/appsettings.json, source/frontend/package-lock.json, source/frontend/package.json, tools/mayan_sync_helper/json_output/mayan_sync.json
Also added json formatted files. I keep seeing them with no format whenever I commit locally
=> Bump version 100

source/backend/entities/Partials/PropertyMgmtActivitySubtype.cs, source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.test.tsx
=> PSP-10137 HOTFIX: Property Management Activity Details - Sub-type is not displayed on the View form

source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/common/__snapshots__/UpdateAcquisitionAgreementForm.test.tsx.snap, source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap, source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap, source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap, source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/__snapshots__/UpdateDispositionSaleView.test.tsx.snap, source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/__snapshots__/ConsultationEditForm.test.tsx.snap, source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap, source/frontend/src/features/mapSideBar/shared/SidebarFooter.tsx, source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap, source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
=> PSP-8716: Reduce Size of Cancel/Save buttons panel

source/frontend/src/components/layout/Healthcheck/HealthcheckContainer.tsx
Added system checks when receiving a 200 - Ok
=> PSP-9900 : PIMS service availability notifications

source/backend/api/Areas/Tools/Controllers/LtsaController.cs, source/backend/tests/unit/api/Controllers/Tools/LtsaControllerTest.cs
=> Ignore pids that cannot be translated to integers.

source/backend/api/Pims.Api.csproj, source/backend/api/Startup.cs, source/backend/api/appsettings.Development.json, source/backend/api/appsettings.Docker.json, source/backend/api/appsettings.Local.json, source/backend/api/appsettings.json, source/backend/core/Extensions/IdentityExtensions.cs, source/backend/tests/core/PrincipalHelper.cs, source/backend/tests/unit/dal/Core/Extensions/IdentityExtensionsTest.cs, source/backend/tests/unit/dal/Repositories/AccessRequestRepositoryTest.cs, source/frontend/src/AppRouter.test.tsx, source/frontend/src/components/common/form/UserRegionSelect/UserRegionSelectContainer.tsx, source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx, source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx, source/frontend/src/hooks/useKeycloakWrapper.tsx, source/frontend/src/utils/test-utils.tsx
see corresponding jira for details.
=> use "sub" instead of idir_user_guid to identify users.

source/backend/api/Pims.Api.csproj, source/frontend/package-lock.json, source/frontend/package.json, source/frontend/src/components/common/mapFSM/useMapSearch.tsx, source/frontend/src/components/maps/MapLeafletView.tsx, source/frontend/src/components/maps/leaflet/Layers/LeafletLayerListener.tsx, source/frontend/src/components/maps/leaflet/VectorTileLayer/EsriVectorTileLayer.tsx
[PSP-10327](https://moti-imb.atlassian.net/browse/PSP-10327)
[PSP-10283](https://moti-imb.atlassian.net/browse/PSP-10283)
=> Test hotfixes

source/backend/api/Pims.Api.csproj, source/backend/api/Services/AcquisitionFileService.cs, source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs, source/backend/dal/Repositories/PropertyRepository.cs, source/frontend/package-lock.json, source/frontend/package.json, source/frontend/src/components/maps/leaflet/LayerPopup/MultiplePropertyPopupView.tsx
=> psp-10349 | common property fixes

source/frontend/src/AppRouter.tsx, source/frontend/src/features/contacts/list/ContactListPage.tsx
=> PSP-10468: FT-REG: React error on Manage Contacts

source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.test.tsx, source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.tsx, source/frontend/src/features/mapSideBar/management/tabs/__snapshots__/ManagementFileTabs.test.tsx.snap, source/frontend/src/features/notes/list/ManagementNoteSummaryView.tsx, source/frontend/src/features/notes/list/NoteListContainer.test.tsx, source/frontend/src/features/notes/list/NoteResults/columns.tsx, source/frontend/src/features/notes/list/PropertyNoteSummaryContainer.tsx, source/frontend/src/features/notes/list/PropertyNoteSummaryView.tsx
=> PSP-10445 File Note Property Summary

source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts, source/frontend/src/components/maps/MapLeafletView.tsx, source/frontend/src/components/maps/leaflet/Control/Search/PropertyQuickInfoContainer.tsx, source/frontend/src/components/maps/leaflet/Control/SearchControl/SearchControl.tsx, source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap, source/frontend/src/features/rightSideLayout/RightSideContainer.tsx, source/frontend/src/utils/mapPropertyUtils.ts
Fixed quick info not showing correctly when no information is available. 
Search bar is now open by default. 
Search button now shows highlighted if there is search data
=> POC Improvements

source/backend/api/Pims.Api.csproj, source/frontend/package-lock.json, source/frontend/package.json, source/frontend/src/components/maps/leaflet/Control/Search/PropertyQuickInfoContainer.tsx, source/frontend/src/hooks/repositories/mapLayer/useHighwayLayer.tsx
psp-10784 correct issue with highway layer
fix null pointer in quick info if title order not present.
=> 5.12 hotfix 1: PSP-10784 correct issue with highway layer

source/frontend/src/components/maps/leaflet/Control/LayersControl/LayerDefinitions.ts, source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx, source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap, source/frontend/src/components/maps/leaflet/Control/LayersControl/types.ts
=> PSP-10598 Add legend for layers with multiple colors

source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditForm.tsx, source/frontend/src/features/mapSideBar/management/tabs/activities/edit/__snapshots__/ManagementActivityEditForm.test.tsx.snap, source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/ActivityDetailSubView.tsx, source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.tsx, source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/__snapshots__/PropertyActivityEditForm.test.tsx.snap
=> PSP-10755: UI/UX rename "Contact Manager" Field
