bcgov/PSP

- frontend/src/components/common/VerticalBar.tsx
- frontend/src/components/layout/Header/EmptyHeader.tsx
- frontend/src/components/layout/Header/Header.tsx
- frontend/src/components/layout/Header/HeaderStyled.tsx
- frontend/src/components/layout/Header/__snapshots__/EmptyHeader.test.tsx.snap
- frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
- frontend/src/features/account/__snapshots__/IENotSupportedPage.test.tsx.snap
- frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
- frontend/src/index.scss
- frontend/src/layouts/EmptyLayout.tsx
- frontend/src/layouts/Footer.tsx
- frontend/src/layouts/Header.test.tsx
- frontend/src/layouts/Header.tsx
- frontend/src/layouts/PublicLayout.scss
- frontend/src/layouts/PublicLayout.tsx
- frontend/src/layouts/__snapshots__/EmptyLayout.test.tsx.snap
- frontend/src/layouts/__snapshots__/Header.test.tsx.snap
- frontend/src/tenants/ITenantConfig.ts
- frontend/src/tenants/config/CITZ.ts
- frontend/src/tenants/config/MOTI.ts
- frontend/src/tenants/config/default.ts
- frontend/src/tenants/tenant.tsx
- frontend/src/tenants/useTenant.test.tsx
- openshift/4.0/templates/app/deploy.yaml
- openshift/4.0/templates/app/tenant-configMap.yaml
The tenant configuration file can now control the background color of the header and footer.
Simply update the `tenant.json` ConfigMap in each environment with a `colour: "your color"`.
> PSP-684 Add tenant environment colour

- openshift/4.0/pipelines/Jenkinsfile.cicd
as requested by @Fosol, this will remove the version prompt unless it is explicitly enabled.
> only prompt for version if the flag is enabled.

- openshift/4.0/pipelines/Jenkinsfile.cicd
Temporarily commenting out the Jenkins pipeline from running the tests and providing the SonarQube scan.  In the next sprint we'll try and add the GitHub Action to submit the SonarQube scan.
I'm still debugging why the Jenkins Slave for DotNet 5.0 doesn't work.  For some reason it cannot restore the Nuget packages in the API.
> Disable Jenkins Pipeline Testing and SonarQube

- .github/workflows/api-dotnetcore.yml
- .github/workflows/app-react.yml
Instead of submitting SonarQube scans with Jenkins we will submit them through GitHub Actions.
The SonarQube scans will only be run on a `push` (i.e. successful merge of a PR).
We cannot currently run the SonarQube scan during a `pull_request` because secrets will not be provided for forks for security reasons.
> PSP-1146 Add SonarQube GitHub Action

- docker-compose.yml
Supporting multiple instances of PIMS is currently impossible due to ports and naming conventions.  This update will allow more flexibility for each developer to control their environment.
This will require you to update your containers.
```bash
make down
make up
```
You can now control your environment ports with `.env`.  However, note that you will need to update other `.env` files to point to the selected ports if you don't use the defaults.
> Update Docker compose configuration

- frontend/public/index.html
- openshift/s2i/nginx-runtime/nginx.conf.template
the current expectation is that all oidc domains are prefixed with the environment. IE:
dev.oidc.gov.bc.ca
test.oidc.gov.bc.ca
this is not the case for prod which is oidc.gov.bc.ca
The usage of * in csps is limited to subdomains of the non-starred section. As a result *.oidc.gov.bc.ca does not match prod (also *oidc.gov.bc.ca is invalid). 
My recommendation is we move up the matcher to *.gov.bc.ca
Another option would be to add an explicit matcher for oidc.gov.bc.ca in addition to *.oidc.gov.bc.ca
> update csp to include a wider match for gov.bc.ca whitelist

- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/constants/strings.tsx
this was introduced with the basemap change. Fix is to set the max zoom level at a value supported by the basemap.
> Correct 404 errors when zooming too far into the new map.

- frontend/src/features/account/LoginStyled.tsx
- frontend/src/features/account/__snapshots__/Login.test.tsx.snap
- frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
This will somewhat address the cutoff issues. 
I've played around with this ticket quite a bit and in order to show 100% of the image the image will be stretched as the container resolution and image resolution are not the same. 
The only other alternatives I could think of is having multiple different images/resolutions and have media queries to provide the user with the appropriate one for their screen size.
I'd suggest we just use one image instead of a collage for 'clean-ness' and consistency's sake but this can do for now depending on what the business wants. Having one image would have less off an impact on different resolutions as we wouldn't be looking for 4 even quadrants etc. 
Let me know if we have any other suggestions for this ticket.
> PSP-1663: Background image 'scaling'

- .editorconfig
- .github/workflows/version.yml
- backend/api/Pims.Api.csproj
- build/.prettierrc.js
- build/README.md
- build/bump-version.js
- frontend/package.json
Implements a new GitHub action to automatically bump the build version number for PRs merged to DEV. 
It uses consistent versioning for backend and frontend sub-projects.
The agreed version number format is:
```
{major}.{minor}.{patch/hotfix}-{ISnumber}.{build}
```
> PSP-1711 automatic versioning

- frontend/src/components/maps/leaflet/PointClusterer.tsx
spiderfied properties are not clickable.
> fix viewing spiderfied properties.

- .github/workflows/version.yml
Made a few adjustments to the auto-increment action:
- It runs only when pull requests are merged (as opposed to any **push** to dev)
- It uses a deploy key with write access to the repo to act as an "admin" user with power to bypass the "no-push" restriction so it can commit the new version number back into the repo automatically
> PSP-1700 Fix automatic versioning action

- frontend/src/features/admin/access-request/AccessRequestPage.tsx
- frontend/src/interfaces/IAccessRequestUserInfo.ts
- frontend/src/interfaces/index.ts
- testing/Profiles/default.glbl
Finally got my docker working so I could test this.
Information given by the `userinfo` fetch at this step was slightly misaligned with the interface we were using at this point causing the `idir` and `last name` to be blank.
Created a new interface to represent the data at this point in time of the access request.
> PSP-2204: Access request auto populate fields

- frontend/src/components/maps/leaflet/Map.tsx
The geo filter contains a key for `STREET_ADDRESS_1` and not `ADDRESS`. Reset was not working for address as it was constantly saying that the filter was unchanged as it was comparing `undefined` to `undefined`.
> PSP-2221: Property Filter - Reset button not clearing properties on map view

- geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/featuretype.xml
- geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/layer.xml
I did not realize this, but it seems like geoserver caches exposes layers, so my update to the location layer in my last PR will not be visible within geoserver. I was able to resolve this locally by recreating the layer, hopefully by propagating that configuration your local dev geoserver's will display the new layer. if not I recommend restarting the container.
> force refresh local geoserver layer.

- frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
- frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
- frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
- frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
- frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
- frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
- frontend/src/features/leases/detail/styles.ts
Stashed code erroneously left out of last PR.
`form-control` currently overriding font weight with `700`, added this to exclude the description text and use appropriate weight of `400`
> Correction to PSP-2361

- frontend/src/features/contacts/contact/detail/Organization.tsx
- frontend/src/features/contacts/contact/detail/Person.tsx
Small "bug" (https://jira.th.gov.bc.ca/browse/PSP-2582).
Just to match the mockup. Previously name appearing like:
`Example OneExample Two`.
Same issue for organizations on an individual.
> PSP-2582: Contact names on new line

- frontend/src/features/admin/edit-user/EditUserPage.test.tsx
- frontend/src/features/admin/edit-user/EditUserPage.tsx
- frontend/src/features/admin/users/ManageUsers.test.tsx
- frontend/src/features/admin/users/ManageUsers.tsx
- frontend/src/interfaces/IUser.ts
After some of the database first changes the business identifier field name underwent some changes. `businessIdentifier` is still being returned and the paged users was trying to map from a non existent (in this case) `businessIdentifierValue`.
I simply added the old value name to the` IUser` interface, but let me know if we should make a separate type and or rename more on the backend.
> PSP-2497: Fix IDIR not displaying

- backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
- backend/entities/Helpers/PersonExtensions.cs
- frontend/src/features/leases/detail/LeasePages/deposits/Deposits.test.tsx
- frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/Deposits.test.tsx.snap
- frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/DepositsReceivedTable.test.tsx
- frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/__snapshots__/DepositsReceivedTable.test.tsx.snap
corresponds to psp-2580. Corrects NPE generated by trying to dereference organization based tenants as if they were persons.
> Do not attempt to return the person name if tenant is not a person.

- frontend/src/colors.scss
Correct draft status colour based off the UX-PIN mockup:
> PSP-2678: Correct draft color

- frontend/src/features/leases/leaseUtils.ts
When adding a tenant to the lease, after saving a middle name of `undefined` would appear. It seems that this only happened from contacts coming from Keycloak as one's entered through the system have a default value of '' and not `undefined`.
> PSP-2721: Handle keycloak undefined middle name

- backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
- frontend/src/components/maps/leaflet/LayerPopup/LayerPopup.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/mapSideBar/MapSideBarContainer.test.tsx
- frontend/src/features/mapSideBar/MapSideBarContainer.tsx
- frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.ts
- frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx
This PR will hide the property information tab in the map slide-out for non-inventory properties. Basically when the API returns an error for a property from the map it means it's not on our inventory. In that case, hide the tab and make LTSA the default selected tab.
Also refactored the way we launch the sidebar to only require a PID instead of a full property object. For non-inventory we have no property object so wouldn't make sense there.
> PSP-2919 Property Details - NON-INVENTORY 

- tools/keycloak/sync/SyncFactory.cs
This will prevent duplicate users from being created.
Also logged the following to cleanup the duplicates:
https://jira.th.gov.bc.ca/browse/PSP-3411
> use the guid instead of the business identifier to id users.

- .github/workflows/api-dotnetcore.yml
- .github/workflows/app-react.yml
For now adding a notification to general when a build fails due to the quality gate. Will monitor and see if that helps.
Also added email notifications to sonarqube, requires developers to add an account to the sonarqube instance.
> add notification to general channel to add visibility to build failures.

- frontend/src/features/research/list/ResearchFilter/ResearchFilter.test.tsx
- frontend/src/features/research/list/ResearchFilter/ResearchFilter.tsx
- frontend/src/features/research/list/ResearchFilter/__snapshots__/ResearchFilter.test.tsx.snap
- frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
Also added a placeholder such that the user is able to clear the status field entirely.
> ensure research file list view searches for active files by default.

- backend/ltsa/LtsaService.cs
Note that I wasn't able to reproduce this in dev or tst even with 10 minutes of continuous usage of the ltsa api. However, I was able to get a rough idea of where the error was being thrown from the error message in the ticket.
> psp-3800 Add additional error handling/logging to JSON parsing.

- backend/api/Areas/Property/Controllers/PropertyController.cs
- backend/dal/Repositories/Interfaces/IPropertyRepository.cs
- backend/dal/Repositories/PropertyRepository.cs
- backend/geocoder/Extensions/ServiceCollectionExtensions.cs
- backend/tests/unit/api/Controllers/Property/PropertyControllerTest.cs
- backend/tests/unit/api/Routes/Property/PropertyControllerTest.cs
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/features/mapSideBar/MotiInventoryContainer.test.tsx
- frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
- frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.tsx
- frontend/src/features/mapSideBar/tabs/propertyDetails/hooks/useGetProperty.ts
- frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
- frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
- frontend/src/features/properties/map/MapView.tsx
- frontend/src/features/properties/map/propertyInformation/PropertyViewSelector.tsx
- frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
- frontend/src/hooks/pims-api/useApiProperties.ts
- frontend/src/hooks/pims-api/useGeoServer.ts
- frontend/src/hooks/useProperties.ts
- frontend/src/hooks/usePropertyAssociations.ts
not all properties in inventory have pids, therefore when we are retrieving properties from our inventory we should use the id if possible.
> update properties screens to use id instead of pid where appropriate.

- backend/api/Pims.Api.csproj
- frontend/package.json
- tools/keycloak/sync/Program.cs
- tools/keycloak/sync/Properties/launchSettings.json
- tools/keycloak/sync/RealmFactory.cs
- tools/keycloak/sync/SyncFactory.cs
keycloak sync was not successfully adding roles to newly created users. This was due to a route change a model change.
> HOTFIX: Fix keycloak sync

- backend/api/Pims.Api.csproj
- frontend/package.json
- tools/keycloak/sync/SyncFactory.cs
When attempting to sync keycloak users, ignore roles failures for roles the exist in KC but not keycloak.
> HOTFIX: Psp 4198

- .github/workflows/api-dotnetcore.yml
All of the errors are related to Pull Request permissions. Works around the issue for now.
> make sonarqube action on push only.

- frontend/src/features/help/components/HelpBox.scss
- frontend/src/features/help/components/HelpBox.tsx
- frontend/src/features/help/components/__snapshots__/HelpBox.test.tsx.snap
> Psp 4237 ensure the help desk arrow is on the same line as the dependent element.

- source/frontend/src/features/properties/map/research/ViewSelector.tsx
Pass formikRef to sub-forms to enable saving and cancelling
> PSP-4800: Property Details Tab and Research Property Tab - Updates cannot be saved

- source/frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.tsx
- source/frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap
> PSP-4855 Property Research - Research Summary section has a different subtitle when in Edit mode

- openshift/4.0/templates/app/deploy.yaml
- source/frontend/src/components/maps/leaflet/LayersControl/__snapshots__/LayersControl.test.tsx.snap
- source/frontend/src/components/maps/leaflet/LayersControl/data.ts
**Deployment Notes:**
The layers for each live env (DEV, TEST, UAT, PROD) are populated from **tenant.json** configuration in OpenShift via a config map. A code change was made to create an empty parent folder for "Legal Highway Research". 
When deploying to live environments double check that the appropriate **tenant.json** config map has been updated in OpenShift
> PSP-4725 Add highway research layers

- openshift/s2i/nginx-runtime/nginx.conf.template
completed additional investigation:
vanity url proxy not source of additional cookie, was able to trace this back to iis server hosting pims layer.
As this layer is proxyied via nginx able to remove cookie at that level.
> HOTFIX: Psp-5235 unable to view map after timing out/logging out of application

- source/backend/api/Configuration/GeoserverProxyOptions.cs
- source/backend/api/Controllers/PimsGeoserverController.cs
- source/backend/api/Pims.Api.csproj
- source/backend/api/Startup.cs
- source/backend/api/appsettings.Local.json
- source/backend/api/appsettings.json
- source/frontend/src/features/mapSideBar/tabs/bcAssessment/BcAssessmentTabView.test.tsx
- source/frontend/src/features/mapSideBar/tabs/bcAssessment/BcAssessmentTabView.tsx
- source/frontend/src/hooks/useBcAssessmentLayer.ts
- source/frontend/src/setupProxy.js
- tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/layer.xml
Based on pattern in the bcgov/crt project
use basic auth and internal route to the geoserver instead of webADE
> Psp 5626 create geoserver map proxy within the PIMS api

- source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx
- source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
The left border of unit # and building rate fields were not visible so fixed the CSS border-left property.
> psp-5356 left border of unit and building fields made visible

- source/frontend/src/components/maps/leaflet/LayersControl/LayersMenu.tsx
Disabled map layer popup from displaying when expand arrow gets clicked on the layer controls.
> psp-5863 remove popup when expand arrow clicked on layer controls

- source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
- source/frontend/src/features/leases/detail/LeasePages/improvements/Improvements.tsx
- source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
Currently, the improvements tab under a lease is divided into 3 sections: Commercial, Other and Residential. And the sections are displayed in that order so this was to make sure that Residential comes before Other.
> psp-6220 fix the order of improvements view form

- .github/workflows/api-dotnetcore.yml
- .github/workflows/app-react.yml
- .github/workflows/ci-cd-pims-dev.yml
- .github/workflows/ci-cd-pims-master.yml
- .github/workflows/ci-cd-pims-test.yml
- .github/workflows/credentials-comment-pr.yml
- .github/workflows/credentials-scan.yml
- .github/workflows/deploy-prod-end.yml
- .github/workflows/depoy-prod-start.yml
- .github/workflows/image-scan-analysis.yml
- .github/workflows/release.yml
- .github/workflows/tag.yml
- .github/workflows/version.yml
Summary of changes:
- Change checkout action to v3
- Replace the MS Teams Notification action (un-maintained) with: https://github.com/marketplace/actions/microsoft-teams-notifications-dc
- The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> HOTFIX: PSP-6343 Update GitHub Actions to run Node16 instead of Node12

- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/CompensationRequisitionTrayContainer.tsx
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/CompensationRequisitionTrayView.tsx
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
* Moved **Generate H120** button to Requisition Details section header
* Minor UI cleanup - namely making financial values (e.g. $15,000) right-aligned as shown on UXPin mockup
> PSP-6493 Generate H120 button is not matching UXPin mockup

- source/backend/api/Models/Concepts/Property/PropertyManagementModel.cs
- source/backend/api/Services/PropertyService.cs
- source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.test.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateContainer.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateForm.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/models.test.ts
- source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/models.ts
- source/frontend/src/mocks/propertyManagement.mock.ts
- source/frontend/src/models/api/Property.ts
- source/frontend/src/utils/propertyUtils.ts
> PSP-7013 Enhance Management Summary >> Lease / License Details

- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/CompensationRequisitionYupSchema.ts
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.tsx
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/financials/FinancialActivitiesSubForm.tsx
- source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
- source/frontend/src/models/api/CompensationFinancial.ts
> PSP-7177 h120 dropdowns typeahead

- source/backend/api/Areas/Documents/DocumentRelationshipController.cs
- source/backend/api/Constants/FileType.cs
- source/backend/api/Services/DocumentFileService.cs
- source/backend/api/Services/DocumentService.cs
- source/backend/api/Services/IDocumentFileService.cs
- source/backend/apimodels/CodeType/DocumentRelationType.cs
- source/backend/apimodels/Models/Concepts/Document/DocumentRelationshipMap.cs
- source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
- source/backend/dal/Repositories/DispositionFileDocumentRepository.cs
- source/backend/dal/Repositories/DocumentRepository.cs
- source/backend/dal/Repositories/Interfaces/IDispositionFileDocumentRepository.cs
- source/backend/entities/Partials/DispositionFileDocument.cs
- source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
- source/backend/tests/unit/api/Services/DocumentServiceTest.cs
- source/backend/tests/unit/dal/Repositories/DispositionFileDocumentRepositoryTest.cs
- source/frontend/src/constants/documentRelationshipType.ts
- source/frontend/src/features/documents/list/DocumentListContainer.tsx
- source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
- source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
- source/frontend/src/features/mapSideBar/shared/tabs/DocumentsTab.tsx
> PSP-6954 disposition documents

- source/backend/api/Services/DispositionFileService.cs
- source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
> psp-7609 ensure that changing the status of a disposition file generates a note

- source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/148_DML_PIMS_DSP_CHKLST_ITEM_TYPE_Alter_Down.sql
- source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/148_DML_PIMS_DSP_CHKLST_ITEM_TYPE_Alter_Up.sql
- source/database/mssql/scripts/dbscripts/PSP_PIMS_S72_00/Alter Down/148_DML_PIMS_DSP_CHKLST_ITEM_TYPE_Alter_Down.sql
- source/database/mssql/scripts/dbscripts/PSP_PIMS_S72_00/Alter Up/148_DML_PIMS_DSP_CHKLST_ITEM_TYPE_Alter_Up.sql
Reordered the display order following the insertion/deletion of the PIMS_DSP_CHKLST_ITEM_TYPE table.
> Added Reordering of the DISPLAY_ORDER Columns

- source/frontend/src/components/Table/Table.tsx
as documented in react-table, this parameter prevents the table from automatically resetting the page when the data changes.
> set table to not reset page when data changes.

- source/frontend/src/features/acquisition/hooks/useAcquisitionFileExport.ts
- source/frontend/src/features/disposition/hooks/useDispositionFileExport.ts
- source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationContainer.test.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationView.test.tsx
> PSP-6920 replace toast with warning modal

- source/backend/api/Services/DispositionFileService.cs
- source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
- source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionForm.tsx
- source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/__snapshots__/UpdateDispositionForm.test.tsx.snap
In this PR the file validation logic was refactored/moved into a separate method to encapsulate all checks in one place. Previous implementation had the checks spread out across several code paths.
Having it in a single method also increases maintainability - if the business rules driving those checks ever change.
> PSP-7922 Completing disposition file - selected properties and errors

- source/frontend/.gitignore
- source/frontend/public/tenants/tenant.json
- source/frontend/src/serviceWorker.ignore.ts
- source/frontend/src/tenants/tenant.tsx
- source/frontend/vite.config.ts
The transition to VITE surfaced a bug loading the **tenant.json** file that contains application configuration information. This file is injected into live environments via a config-map. However, in local development we use a hard-coded typescript file with the configuration (which made it harder to reproduce this issue locally)
This PR:
- fixes the loading of tenant.json (PUBLIC_URL env var is not available in vite)
- adds a default tenant.json for local development 
- this can be achieved by deleting the env var `VITE_TENANT=MOTI` from your env file. If you keep the env var, then the hard-coded configuration will be used.
> PSP-8198 tenant json loading bug

- source/frontend/src/tenants/tenant.tsx
- source/frontend/vite.config.ts
Load **tenant.json** from root URL. Also disable gzip compression of json files because we override the original json on OpenShift but if the gzip remains, it takes precedence over the override.
> PSP-8198 Vite fix

- source/frontend/src/features/properties/map/MapContainer.tsx
- source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
This was a weird asset loading bug caused by migration to **vite**. Inlined SVGs are converted to data URLs when small enough (< 4kb) and those data urls need to be surrounded with quotes - ie in CSS: 
```css
.c0.draft-cursor .leaflet-interactive {
cursor: url("data:image/svg+xml, ...") 15 45, pointer;
}
```
our code was missing those quotes in the CSS for `url()` and so the icon was not loading on production builds. launching the frontend via "npm start" locally does not show this bug because the asset/svg is loaded via an URL in development mode (vs a data URL).
> PSP-8203 FT: map icon that hovers when you try to choose property on the map is not displayed

- source/frontend/src/features/leases/detail/LeasePages/insurance/details/Insurance.test.tsx
- source/frontend/src/features/leases/detail/LeasePages/insurance/details/Policy.tsx
- source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
- source/frontend/src/features/leases/detail/LeasePages/insurance/edit/EditInsuranceContainer.test.tsx
- source/frontend/src/features/leases/detail/LeasePages/insurance/edit/EditInsuranceContainer.tsx
- source/frontend/src/features/leases/detail/LeasePages/insurance/edit/InsuranceForm.tsx
- source/frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditInsuranceContainer.test.tsx.snap
- source/frontend/src/features/leases/detail/LeasePages/insurance/edit/models.ts
> PSP-7493 lease insurance UI cleanup

- source/backend/api/Models/Configuration/MayanConfig.cs
- source/backend/api/Repositories/Mayan/IEdmsDocumentRepository.cs
- source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
- source/backend/api/Services/DocumentService.cs
- source/backend/api/appsettings.json
- source/frontend/src/assets/scss/App.scss
- source/frontend/src/features/documents/DocumentPreviewView.tsx
By default, Mayan will only cache document pages on a schedule, or when they are requested. This adds an async pre-cache task to the upload action to facilitate that - greatly increasing the odds that a page preview will be ready when requested.
> pims document preview - pre-cache.

- source/backend/api/Pims.Api.csproj
- source/frontend/package.json
- source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
- source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
- source/frontend/src/components/maps/MapLeafletView.tsx
- source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
- source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
- source/frontend/src/components/maps/leaflet/Layers/useConfiguredMapLayers.tsx
- source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
- source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
- source/frontend/src/mocks/mapFSM.mock.ts
- tools/geoserver/geoserver_data/psp/settings.xml
see commits for story definitions.
> Psp 8635, psp-8636, psp-8638

- source/backend/api/Areas/Reports/Controllers/LeaseController.cs
- source/backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
- source/backend/dal/Repositories/LeaseRepository.cs
- source/backend/dal/Repositories/PropertyLeaseRepository.cs
- source/backend/entities/Extensions/LeaseExtensions.cs
- source/backend/tests/unit/dal/Core/Extensions/LeaseExtensionsTest.cs
- source/frontend/src/features/leases/leaseUtils.ts
- source/frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
- source/frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
- source/frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
- source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
- source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLicenceOfOccupation.ts
- source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
- source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/LeaseAssociationContent.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.test.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
- source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
- source/frontend/src/models/generate/lease/GenerateLease.test.ts
- source/frontend/src/models/generate/lease/GenerateLease.ts
Updated lease expiry search to use renewal information. Updated expiry definition for leases
> psp-8771 & psp-8683  | Lease expiry using renewal information

- etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs.dtproj
- etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs.dtproj.user
- etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs.dtsx
- etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs.sln
- etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PRE_ETL_CREATE_TEMP_Tables.dtsx
- etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/Project.params
> PSP-8704 changes

- .github/workflows/api-dotnetcore.yml
- .github/workflows/app-logging.yml
- .github/workflows/app-react.yml
- .github/workflows/ci-cd-pims-dev.yml
- .github/workflows/ci-cd-pims-master.yml
- .github/workflows/credentials-comment-pr.yml
- .github/workflows/credentials-scan.yml
- .github/workflows/db-schma.yml
- .github/workflows/deploy-prod-end.yml
- .github/workflows/deploy-prod-start.yml
- .github/workflows/image-scan-analysis.yml
- .github/workflows/integration-test.yml
- .github/workflows/keycloak-sync.yml
- .github/workflows/mayan-sync.yml
- .github/workflows/release.yml
- .github/workflows/retag-dev-to-test.yml
- .github/workflows/retag-test-to-uat.yml
- .github/workflows/tag.yml
- .github/workflows/uat_hotfix.yml
- .github/workflows/uat_pre_release_hotfix.yml
- .github/workflows/version.yml
This gets rid of a number of warnings we are seeing on our CI/CD pipelines:
* https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
* https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> PIMS devops updates

- Makefile
- source/backend/api/Areas/Property/Models/PropertyFilterModel.cs
- source/backend/dal/Helpers/Extensions/PropertyViewExtensions.cs
- source/backend/dal/Models/PropertyFilter.cs
- source/backend/dal/Repositories/PropertyRepository.cs
- source/backend/tests/core/DatabaseHelper.cs
- source/backend/tests/core/Entities/PropertyHelper.cs
- source/backend/tests/core/PimsTestContext.cs
- source/backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
- source/backend/tests/unit/api/Controllers/Reports/PropertyControllerTest.cs
- source/backend/tests/unit/dal/Entities/PropertyFilterTest.cs
- source/backend/tests/unit/dal/Repositories/PropertyActivityRepositoryTest.cs
- source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
- source/frontend/src/components/common/List/SelectInput.test.tsx
- source/frontend/src/components/common/List/__snapshots__/SelectInput.test.tsx.snap
- source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
- source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
- source/frontend/src/features/properties/filter/IPropertyFilter.ts
- source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
- source/frontend/src/features/properties/filter/PropertyFilter.tsx
- source/frontend/src/features/properties/filter/PropertySearchToggle.tsx
- source/frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
- source/frontend/src/features/properties/list/PropertyListView.test.tsx
- source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
> PSP-9452: Split map search for PID PIN

- .github/workflows/ci-cd-pims-dev.yml
- .github/workflows/deploy-prod-start-argo.yml
As part of the move to ArgoCD, all containers have a suffix (ie "-dev", "-prod" etc).
This change fixes the keycloak-sync call for DEV and PROD (the other environments are okay)
> Fix keycloak-sync call in GitHub actions

- source/backend/dal/Helpers/Extensions/DbContextExtensions.cs
- source/backend/dal/Repositories/UserRepository.cs
discussed in person some time ago.
Only uses are in user update and user delete.
User delete unused, tested user update continues to work.
> SetOriginalConcurrencyControlNumber function removal

- .github/workflows/api-dotnetcore.yml
- .github/workflows/app-logging.yml
- .github/workflows/app-react.yml
- .github/workflows/ci-cd-pims-dev.yml
- .github/workflows/codecov-comment-pr.yml
- .github/workflows/credentials-comment-pr.yml
- .github/workflows/credentials-scan.yml
- .github/workflows/db-schma.yml
- .github/workflows/deploy-prod-end.yml
- .github/workflows/deploy-prod-start-argo.yml
- .github/workflows/deploy-prod-start.yml
- .github/workflows/image-scan-analysis.yml
- .github/workflows/integration-test.yml
- .github/workflows/keycloak-sync.yml
- .github/workflows/mayan-sync.yml
- .github/workflows/release.yml
- .github/workflows/retag-dev-to-test.yml
- .github/workflows/retag-test-to-uat-argo.yml
- .github/workflows/retag-test-to-uat.yml
- .github/workflows/tag.yml
- .github/workflows/uat_hotfix.yml
- .github/workflows/uat_hotfix_argo.yml
- .github/workflows/uat_pre_release_hotfix.yml
- .github/workflows/uat_pre_release_hotfix_argo.yml
- .github/workflows/version.yml
- .github/workflows/zap-scan.yml
Revert to using older `ubuntu-22.04` runner image because the newest "latest" has removed a lot of required dependencies
> [CI] Fix build failures after ubuntu-latest upgrade to 24.04

- source/backend/api/Services/DocumentQueueService.cs
- source/backend/dal/Repositories/DocumentQueueRepository.cs
- source/backend/tests/unit/api/Services/DocumentQueueServiceTest.cs
1. (process 1) upload document action starts upload, sets document to processing 
2. (process 2) document poll starts executing with document in processing state 
3.  (process 1) upload document action completes upload, sets document to sucess. 
4.  (process 2) document poll throws concurrency exception.
> Address race condition where: (see comment)

- source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
- source/backend/api/Services/CompensationRequisitionService.cs
- source/backend/dal/Repositories/CompReqFinancialRepository.cs
- source/backend/dal/Repositories/CompensationRequisitionRepository.cs
- source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
- source/backend/tests/unit/dal/Repositories/CompensationRequisitionRepositoryTest.cs
- source/backend/tests/unit/dal/Repositories/ConsultationRepositoryTest.cs
> PSP-9683 Generated H-120 Compensation Requisition not Populating Electoral District

- source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
- source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
> PSP-8351: Expand Visible Text Under the Intended Use Field (L/L)

- source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
- source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
The spacing fix for the overlapping issue was fixed by PSP-9486
> PSP-9478: Changing zoom map tooltip and title on the Property Information leaflet

- source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
- source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/__snapshots__/FilterContentForm.test.tsx.snap
https://github.com/user-attachments/assets/145972d7-b23a-499f-bfd4-a75a1c30cba3
> PSP-9803 UI UX: Advanced Filter Map - Reset to Default Button icon

- source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyForm.test.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyForm.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyResearchContainer.test.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyResearchContainer.tsx
- source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyYupSchema.ts
- source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/__snapshots__/UpdatePropertyForm.test.tsx.snap
- source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/models.ts
- source/frontend/src/features/mapSideBar/router/FilePropertyRouter.tsx
- source/frontend/src/mocks/researchFile.mock.ts
> PSP-9815 Property Research Summary comments field doesn't have a limit of character when more than allowed are inserted. 

- source/backend/api/Pims.Api.csproj
- source/frontend/package.json
- source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
This issue would issue a request to the pims location layer with no pid/pin filter, which would then request all properties in PIMS, and then return the first property.
> HOTFIX psp-9865 - fix map click loading logic.

- source/database/mssql/scripts/dbscripts/deploy.sh
- source/database/mssql/scripts/dbscripts/generate_master_sql.sh
- source/database/mssql/scripts/dbscripts/setup.sh
- source/database/mssql/scripts/dbscripts/upgrade.sh
> DB Scripts - Fix alphanumeric sorting for folders S100 and greater
